// src/kanban-solid/src/components/modals/BestOfNDetailModal.tsx
/**
 * BestOfNDetailModal Component - Best-of-N execution details
 * Ported from React to SolidJS
 */

import { createSignal, createEffect, For, Show } from 'solid-js'
import { ModalWrapper } from '@/components/common/ModalWrapper'
import { uiStore } from '@/stores'
import { tasksApi } from '@/api'
import type { Task, BestOfNSummary, TaskRun, Candidate } from '@/types'

interface BestOfNDetailModalProps {
  task?: Task
  onClose: () => void
  onSelectWinner: (sessionId: string) => Promise<void>
}

export function BestOfNDetailModal(props: BestOfNDetailModalProps) {
  const [summary, setSummary] = createSignal<BestOfNSummary | null>(null)
  const [taskRuns, setTaskRuns] = createSignal<TaskRun[]>([])
  const [candidates, setCandidates] = createSignal<Candidate[]>([])
  const [isLoading, setIsLoading] = createSignal(true)
  const [isSelecting, setIsSelecting] = createSignal(false)

  const taskId = () => props.task?.id

  createEffect(() => {
    const id = taskId()
    if (!id) return

    const loadData = async () => {
      setIsLoading(true)
      try {
        const [summaryData, runsData, candidatesData] = await Promise.all([
          tasksApi.getBestOfNSummary(id),
          tasksApi.getTaskRuns(id),
          tasksApi.getTaskCandidates(id),
        ])
        setSummary(summaryData)
        setTaskRuns(runsData)
        setCandidates(candidatesData)
      } catch (e) {
        uiStore.showToast('Failed to load details', 'error')
      } finally {
        setIsLoading(false)
      }
    }
    loadData()
  })

  const handleSelectWinner = async (candidateId: string) => {
    setIsSelecting(true)
    try {
      await props.onSelectWinner(candidateId)
      uiStore.showToast('Winner selected', 'success')
    } catch (e) {
      uiStore.showToast('Failed to select winner', 'error')
    } finally {
      setIsSelecting(false)
    }
  }

  return (
    <ModalWrapper title={`Best-of-N: ${props.task?.name || taskId() || 'Unknown'}`} onClose={props.onClose} size="lg">
      <div class="space-y-4 max-h-[60vh] overflow-y-auto">
        <Show
          when={!isLoading()}
          fallback={<div class="text-center py-8 text-dark-text-muted">Loading details...</div>}
        >
          <Show
            when={summary()}
            fallback={<div class="text-center py-8 text-dark-text-muted">No Best-of-N data for this task.</div>}
          >
            <div class="grid grid-cols-3 gap-4">
              <div class="stat-card">
                <div class="stat-value">{summary()!.workersDone}/{summary()!.workersTotal}</div>
                <div class="stat-label">Workers</div>
              </div>
              <div class="stat-card">
                <div class="stat-value">{summary()!.reviewersDone}/{summary()!.reviewersTotal}</div>
                <div class="stat-label">Reviewers</div>
              </div>
              <div class="stat-card">
                <div class="stat-value">{summary()!.availableCandidates}</div>
                <div class="stat-label">Candidates</div>
              </div>
            </div>

            <div class="border-t border-dark-border pt-4">
              <h4 class="text-sm font-medium mb-2">Task Runs</h4>
              <Show
                when={taskRuns().length > 0}
                fallback={<div class="text-dark-text-muted text-sm">No task runs yet.</div>}
              >
                <For each={taskRuns()}>
                  {(run) => (
                    <div class="session-entry mb-2">
                      <div class="flex items-center gap-2">
                        <span class={`w-2 h-2 rounded-full ${
                          run.status === 'done' ? 'bg-accent-success' :
                          run.status === 'failed' ? 'bg-accent-danger' :
                          run.status === 'running' ? 'bg-accent-warning' :
                          'bg-dark-text-muted'
                        }`} />
                        <span class="text-sm">{run.phase}</span>
                        <span class="text-xs text-dark-text-muted">({run.status})</span>
                      </div>
                    </div>
                  )}
                </For>
              </Show>
            </div>

            <div class="border-t border-dark-border pt-4">
              <h4 class="text-sm font-medium mb-2">Candidates</h4>
              <Show
                when={candidates().length > 0}
                fallback={<div class="text-dark-text-muted text-sm">No candidates yet.</div>}
              >
                <For each={candidates()}>
                  {(candidate) => (
                    <div class="session-entry mb-2">
                      <div class="flex items-center justify-between">
                        <span class={`text-sm ${
                          candidate.status === 'selected' ? 'text-accent-success' :
                          candidate.status === 'rejected' ? 'text-accent-danger' :
                          'text-dark-text'
                        }`}>
                          {candidate.status === 'selected' ? '✓ ' : ''}
                          Candidate {candidate.id.slice(0, 8)}
                        </span>
                        <div class="flex items-center gap-2">
                          <span class="text-xs text-dark-text-muted">({candidate.status})</span>
                          <Show when={candidate.status === 'pending'}>
                            <button
                              class="btn btn-xs btn-primary"
                              onClick={() => handleSelectWinner(candidate.id)}
                              disabled={isSelecting()}
                            >
                              {isSelecting() ? '...' : 'Select'}
                            </button>
                          </Show>
                        </div>
                      </div>
                    </div>
                  )}
                </For>
              </Show>
            </div>
          </Show>
        </Show>
      </div>
    </ModalWrapper>
  )
}

// src/kanban-react/src/components/modals/BestOfNDetailModal.tsx
import { useState, useEffect } from 'react'
import { ModalWrapper } from '../common/ModalWrapper'
import { useTasksContext, useToastContext } from '@/contexts/AppContext'
import { useApi } from '@/hooks'
import type { BestOfNSummary, TaskRun, Candidate } from '@/types'

interface BestOfNDetailModalProps {
  taskId: string
  onClose: () => void
}

export function BestOfNDetailModal({ taskId, onClose }: BestOfNDetailModalProps) {
  const tasks = useTasksContext()
  const api = useApi()
  const toasts = useToastContext()
  const [summary, setSummary] = useState<BestOfNSummary | null>(null)
  const [taskRuns, setTaskRuns] = useState<TaskRun[]>([])
  const [candidates, setCandidates] = useState<Candidate[]>([])
  const [isLoading, setIsLoading] = useState(true)

  const task = tasks.getTaskById(taskId)

  useEffect(() => {
    const loadData = async () => {
      setIsLoading(true)
      try {
        const [summaryData, runsData, candidatesData] = await Promise.all([
          api.getBestOfNSummary(taskId),
          api.getTaskRuns(taskId),
          api.getTaskCandidates(taskId),
        ])
        setSummary(summaryData)
        setTaskRuns(runsData)
        setCandidates(candidatesData)
      } catch (e) {
        toasts.showToast('Failed to load details', 'error')
      } finally {
        setIsLoading(false)
      }
    }
    loadData()
  }, [taskId, api, toasts])

  return (
    <ModalWrapper title={`Best-of-N: ${task?.name || taskId}`} onClose={onClose} size="lg">
      <div className="space-y-4 max-h-[60vh] overflow-y-auto">
        {isLoading ? (
          <div className="text-center py-8 text-dark-text-muted">Loading details...</div>
        ) : !summary ? (
          <div className="text-center py-8 text-dark-text-muted">No Best-of-N data for this task.</div>
        ) : (
          <>
            <div className="grid grid-cols-3 gap-4">
              <div className="stat-card">
                <div className="stat-value">{summary.workersDone}/{summary.workersTotal}</div>
                <div className="stat-label">Workers</div>
              </div>
              <div className="stat-card">
                <div className="stat-value">{summary.reviewersDone}/{summary.reviewersTotal}</div>
                <div className="stat-label">Reviewers</div>
              </div>
              <div className="stat-card">
                <div className="stat-value">{summary.availableCandidates}</div>
                <div className="stat-label">Candidates</div>
              </div>
            </div>

            <div className="border-t border-dark-border pt-4">
              <h4 className="text-sm font-medium mb-2">Task Runs</h4>
              {taskRuns.length === 0 ? (
                <div className="text-dark-text-muted text-sm">No task runs yet.</div>
              ) : (
                taskRuns.map(run => (
                  <div key={run.id} className="session-entry mb-2">
                    <div className="flex items-center gap-2">
                      <span className={`w-2 h-2 rounded-full ${
                        run.status === 'done' ? 'bg-accent-success' :
                        run.status === 'failed' ? 'bg-accent-danger' :
                        run.status === 'running' ? 'bg-accent-warning' :
                        'bg-dark-text-muted'
                      }`} />
                      <span className="text-sm">{run.phase}</span>
                      <span className="text-xs text-dark-text-muted">({run.status})</span>
                    </div>
                  </div>
                ))
              )}
            </div>

            <div className="border-t border-dark-border pt-4">
              <h4 className="text-sm font-medium mb-2">Candidates</h4>
              {candidates.length === 0 ? (
                <div className="text-dark-text-muted text-sm">No candidates yet.</div>
              ) : (
                candidates.map(candidate => (
                  <div key={candidate.id} className="session-entry mb-2">
                    <div className="flex items-center justify-between">
                      <span className={`text-sm ${
                        candidate.status === 'selected' ? 'text-accent-success' :
                        candidate.status === 'rejected' ? 'text-accent-danger' :
                        'text-dark-text'
                      }`}>
                        {candidate.status === 'selected' ? '✓ ' : ''}
                        Candidate {candidate.id.slice(0, 8)}
                      </span>
                      <span className="text-xs text-dark-text-muted">({candidate.status})</span>
                    </div>
                  </div>
                ))
              )}
            </div>
          </>
        )}
      </div>
    </ModalWrapper>
  )
}
