// src/kanban-solid/src/components/modals/ConfirmModal.tsx
/**
 * ConfirmModal Component - Generic confirmation dialog
 */

import { Show } from 'solid-js'
import { ModalWrapper } from '../common/ModalWrapper'

interface ConfirmModalProps {
  isOpen: boolean
  action: 'delete' | 'archive' | 'convertToTemplate'
  taskName: string
  onConfirm: () => void
  onClose: () => void
}

export function ConfirmModal(props: ConfirmModalProps) {
  const title = () => {
    if (props.action === 'delete') return 'Confirm Delete'
    if (props.action === 'archive') return 'Confirm Archive'
    return 'Convert to Template'
  }
  
  const message = () => {
    if (props.action === 'delete') {
      return `Are you sure you want to delete "${props.taskName}"? This cannot be undone.`
    }
    if (props.action === 'archive') {
      return `Are you sure you want to archive "${props.taskName}"? Archived tasks can be viewed in the Archived tab.`
    }
    return `Convert "${props.taskName}" to a template? The task will be moved to the Templates column.`
  }
  
  const buttonClass = () => {
    if (props.action === 'delete') return 'btn btn-danger'
    if (props.action === 'archive') return 'btn btn-primary'
    return 'btn btn-primary'
  }
  
  const buttonText = () => {
    if (props.action === 'delete') return 'Delete'
    if (props.action === 'archive') return 'Archive'
    return 'Convert'
  }

  return (
    <Show when={props.isOpen}>
      <ModalWrapper title={title()} onClose={props.onClose} size="sm">
        <p class="text-dark-text-secondary mb-6">{message()}</p>

        <div class="modal-footer">
          <button class="btn" onClick={props.onClose}>
            Cancel
          </button>
          <button
            class={buttonClass()}
            onClick={props.onConfirm}
          >
            {buttonText()}
          </button>
        </div>
      </ModalWrapper>
    </Show>
  )
}

// src/kanban-react/src/components/modals/ConfirmModal.tsx
import { ModalWrapper } from '../common/ModalWrapper'

interface ConfirmModalProps {
  isOpen: boolean
  action: 'delete' | 'archive' | 'convertToTemplate'
  taskName: string
  onClose: () => void
  onConfirm: () => void
}

export function ConfirmModal({ isOpen, action, taskName, onClose, onConfirm }: ConfirmModalProps) {
  if (!isOpen) return null

  const title = action === 'delete' ? 'Delete Task' : action === 'archive' ? 'Archive Task' : 'Convert to Template'
  const message = action === 'delete'
    ? `Are you sure you want to delete "${taskName}"? This action cannot be undone.`
    : action === 'archive'
    ? `Are you sure you want to archive "${taskName}"? Archived tasks can be viewed in the Archived tab.`
    : `Convert "${taskName}" to a template? The task will be moved to the Templates column.`
  const confirmText = action === 'delete' ? 'Delete' : action === 'archive' ? 'Archive' : 'Convert'
  const confirmClass = action === 'delete' ? 'btn-danger' : action === 'archive' ? 'btn-primary' : 'btn-primary'

  return (
    <ModalWrapper title={title} onClose={onClose} size="sm">
      <div className="space-y-4">
        <p className="text-dark-text">{message}</p>
        <p className="text-sm text-dark-text-muted">
          Tip: Hold Ctrl/Cmd and click to skip this confirmation in the future.
        </p>

        <div className="modal-footer">
          <button type="button" className="btn" onClick={onClose}>Cancel</button>
          <button type="button" className={`btn ${confirmClass}`} onClick={onConfirm}>
            {confirmText}
          </button>
        </div>
      </div>
    </ModalWrapper>
  )
}
