// src/kanban-vue/src/components/modals/RevisionModal.vue
<script setup lang="ts">
import { ref, computed, inject } from 'vue'
import type { useTasks } from '@/composables/useTasks'
import type { useToasts } from '@/composables/useToasts'

const props = defineProps<{
  taskId: string
}>()

const emit = defineEmits<{
  close: []
}>()

const tasks = inject<ReturnType<typeof useTasks>>('tasks')!
const toasts = inject<ReturnType<typeof useToasts>>('toasts')!

const feedback = ref('')
const isLoading = ref(false)

const task = computed(() => tasks.getTaskById(props.taskId))
const taskName = computed(() => task.value?.name || props.taskId)

const confirm = async () => {
  if (!feedback.value.trim()) {
    toasts.showToast('Feedback cannot be empty', 'error')
    return
  }

  isLoading.value = true
  try {
    await tasks.requestPlanRevision(props.taskId, feedback.value.trim())
    toasts.showToast('Revision requested', 'success')
    emit('close')
  } catch (e) {
    toasts.showToast('Request revision failed: ' + (e instanceof Error ? e.message : String(e)), 'error')
  } finally {
    isLoading.value = false
  }
}

const closeOnOverlay = (e: MouseEvent) => {
  if (e.target === e.currentTarget) {
    emit('close')
  }
}
</script>

<template>
  <div class="modal-overlay" @mousedown="closeOnOverlay">
    <div class="modal w-[440px]">
      <div class="modal-header">
        <h2>Request Plan Changes</h2>
        <button class="modal-close" @click="emit('close')">×</button>
      </div>

      <div class="modal-body">
        <div class="mb-3 text-sm">{{ taskName }}</div>
        <label class="block text-sm text-dark-text-muted mb-1.5">
          What should be changed?
        </label>
        <textarea
          v-model="feedback"
          rows="4"
          class="form-textarea"
          placeholder="Describe the changes you want in the plan..."
        />
      </div>

      <div class="modal-footer">
        <button class="btn" @click="emit('close')">Cancel</button>
        <button
          class="btn"
          style="border-color: #f59e0b; color: #f59e0b;"
          :disabled="isLoading"
          @click="confirm"
        >
          {{ isLoading ? 'Sending...' : 'Send Feedback' }}
        </button>
      </div>
    </div>
  </div>
</template>

// src/kanban-react/src/components/modals/RevisionModal.tsx
import { useState } from 'react'
import { ModalWrapper } from '../common/ModalWrapper'
import { useTasksContext, useToastContext } from '@/contexts/AppContext'

interface RevisionModalProps {
  taskId: string
  onClose: () => void
}

export function RevisionModal({ taskId, onClose }: RevisionModalProps) {
  const tasks = useTasksContext()
  const toasts = useToastContext()
  const [feedback, setFeedback] = useState('')
  const [isLoading, setIsLoading] = useState(false)

  const task = tasks.getTaskById(taskId)

  const handleRequestRevision = async () => {
    if (!feedback.trim()) {
      toasts.showToast('Please provide feedback for the revision', 'error')
      return
    }

    setIsLoading(true)
    try {
      await tasks.requestPlanRevision(taskId, feedback)
      toasts.showToast('Revision requested', 'success')
      onClose()
    } catch (e) {
      toasts.showToast(e instanceof Error ? e.message : 'Failed to request revision', 'error')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <ModalWrapper title={`Request Revision: ${task?.name || taskId}`} onClose={onClose}>
      <div className="space-y-4">
        <div className="form-group">
          <label>Revision Feedback</label>
          <textarea
            className="form-textarea"
            value={feedback}
            onChange={(e) => setFeedback(e.target.value)}
            rows={6}
            placeholder="Describe what needs to be revised in the plan..."
            required
          />
        </div>

        <div className="modal-footer">
          <button type="button" className="btn" onClick={onClose} disabled={isLoading}>Cancel</button>
          <button 
            type="button" 
            className="btn btn-primary" 
            onClick={handleRequestRevision}
            disabled={isLoading}
          >
            {isLoading ? 'Requesting...' : 'Request Revision'}
          </button>
        </div>
      </div>
    </ModalWrapper>
  )
}
