// src/kanban-react/src/components/common/ModelPicker.tsx
import { useState, useRef, useEffect, useCallback } from 'react'
import type { ModelEntry } from '@/types'
import { useModelSearch } from '@/hooks'
import { HelpButton } from './HelpButton'

interface ModelPickerProps {
  modelValue: string
  label: string
  help?: string
  disabled?: boolean
  onUpdate: (value: string) => void
}

export function ModelPicker({ modelValue, label, help, disabled, onUpdate }: ModelPickerProps) {
  const modelSearch = useModelSearch()
  const [query, setQuery] = useState(modelValue)
  const [showDropdown, setShowDropdown] = useState(false)
  const [isMouseDown, setIsMouseDown] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    setQuery(modelValue)
  }, [modelValue])

  const suggestions = modelSearch.getSuggestions(query, 12)

  const handleFocus = useCallback(() => {
    if (!disabled) {
      setShowDropdown(true)
    }
  }, [disabled])

  const handleBlur = useCallback(() => {
    // Delay to allow clicking on dropdown items
    setTimeout(() => {
      if (!isMouseDown) {
        setShowDropdown(false)
        const normalized = modelSearch.normalizeValue(query)
        if (normalized !== modelValue) {
          onUpdate(normalized)
        }
      }
    }, 200)
  }, [query, modelValue, modelSearch, onUpdate, isMouseDown])

  const handleInputChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value
    setQuery(value)
    setShowDropdown(true)
  }, [])

  const handleSelect = useCallback((value: string) => {
    setQuery(value)
    onUpdate(value)
    setShowDropdown(false)
    setIsMouseDown(false)
    inputRef.current?.blur()
  }, [onUpdate])

  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    // Prevent blur from firing when clicking dropdown
    if (showDropdown) {
      setIsMouseDown(true)
    }
  }, [showDropdown])

  const handleMouseUp = useCallback(() => {
    setIsMouseDown(false)
  }, [])

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        setShowDropdown(false)
      }
    }

    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  return (
    <div className="form-group" ref={containerRef}>
      <div className="label-row">
        <label>{label}</label>
        {help && <HelpButton tooltip={help} />}
      </div>
      <div className="relative">
        <input
          ref={inputRef}
          type="text"
          className="form-input"
          placeholder="Type model name..."
          disabled={disabled}
          value={query}
          onChange={handleInputChange}
          onFocus={handleFocus}
          onBlur={handleBlur}
        />
        {showDropdown && suggestions.length > 0 && (
          <div
            className="absolute top-full left-0 right-0 mt-1 bg-[#1a1a1a] border border-dark-surface3 rounded-lg shadow-lg z-[100] max-h-48 overflow-y-auto"
            onMouseDown={handleMouseDown}
            onMouseUp={handleMouseUp}
          >
            {suggestions.map((suggestion: ModelEntry) => (
              <div
                key={`${suggestion.value}-${suggestion.providerId}`}
                className="px-3 py-2 text-sm cursor-pointer hover:bg-accent-primary/10"
                onClick={() => handleSelect(suggestion.value)}
              >
                <div className="font-medium">{suggestion.label}</div>
                {suggestion.providerName && suggestion.providerName !== 'default' && (
                  <div className="text-xs text-dark-text-muted">
                    {suggestion.providerName}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

// src/kanban-solid/src/components/common/ModelPicker.tsx
/**
 * ModelPicker Component - AI model selection with search
 * Ported from React to SolidJS
 */

import { createSignal, createEffect, onMount, Show, For } from 'solid-js'
import { createQuery } from '@tanstack/solid-query'
import Fuse from 'fuse.js'
import { referenceApi } from '@/api'
import { HelpButton } from './HelpButton'
import type { ModelEntry } from '@/types'

interface ModelPickerProps {
  modelValue: string
  label: string
  help?: string
  disabled?: boolean
  onUpdate: (value: string) => void
}

export function ModelPicker(props: ModelPickerProps) {
  const [query, setQuery] = createSignal(props.modelValue)
  const [showDropdown, setShowDropdown] = createSignal(false)
  const [isMouseDown, setIsMouseDown] = createSignal(false)
  const [fuse, setFuse] = createSignal<Fuse<ModelEntry> | null>(null)
  let inputRef: HTMLInputElement | undefined
  let containerRef: HTMLDivElement | undefined

  const modelsQuery = createQuery(() => ({
    queryKey: ['models'],
    queryFn: () => referenceApi.getModels(),
    staleTime: 60000,
  }))

  // Build fuse index when models load
  createEffect(() => {
    const catalog = modelsQuery.data
    if (!catalog) return

    const searchIndex: ModelEntry[] = []
    for (const provider of catalog.providers) {
      for (const model of provider.models) {
        searchIndex.push({
          ...model,
          providerId: provider.id,
          providerName: provider.name,
        })
      }
    }

    const fuseInstance = new Fuse(searchIndex, {
      keys: ['label', 'value', 'providerName'],
      threshold: 0.4,
    })
    setFuse(fuseInstance)
  })

  // Update query when modelValue changes
  createEffect(() => {
    setQuery(props.modelValue)
  })

  const suggestions = (): ModelEntry[] => {
    const fuseInstance = fuse()
    if (!fuseInstance) return []
    if (!query()) {
      return fuseInstance.getIndex().docs.slice(0, 12)
    }
    const results = fuseInstance.search(query(), { limit: 12 })
    return results.map(r => r.item)
  }

  const handleFocus = () => {
    if (!props.disabled) {
      setShowDropdown(true)
    }
  }

  const handleBlur = () => {
    // Delay to allow clicking on dropdown items
    setTimeout(() => {
      if (!isMouseDown()) {
        setShowDropdown(false)
        normalizeAndUpdate()
      }
    }, 200)
  }

  const normalizeAndUpdate = () => {
    const catalog = modelsQuery.data
    if (!catalog) return

    const normalized = query().toLowerCase().trim()
    const searchIndex: ModelEntry[] = []
    for (const provider of catalog.providers) {
      for (const model of provider.models) {
        searchIndex.push({
          ...model,
          providerId: provider.id,
          providerName: provider.name,
        })
      }
    }

    const found = searchIndex.find(m =>
      m.value.toLowerCase() === normalized ||
      m.label.toLowerCase() === normalized
    )

    const finalValue = found?.value || query()
    if (finalValue !== props.modelValue) {
      props.onUpdate(finalValue)
    }
  }

  const handleInputChange = (e: Event) => {
    const value = (e.target as HTMLInputElement).value
    setQuery(value)
    setShowDropdown(true)
  }

  const handleSelect = (value: string) => {
    setQuery(value)
    props.onUpdate(value)
    setShowDropdown(false)
    setIsMouseDown(false)
    inputRef?.blur()
  }

  const handleMouseDown = () => {
    if (showDropdown()) {
      setIsMouseDown(true)
    }
  }

  const handleMouseUp = () => {
    setIsMouseDown(false)
  }

  // Close dropdown when clicking outside
  const handleClickOutside = (e: MouseEvent) => {
    if (containerRef && !containerRef.contains(e.target as Node)) {
      setShowDropdown(false)
    }
  }

  onMount(() => {
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  })

  return (
    <div class="form-group" ref={containerRef}>
      <div class="label-row">
        <label>{props.label}</label>
        <Show when={props.help}>
          <HelpButton tooltip={props.help!} />
        </Show>
      </div>
      <div class="relative">
        <input
          ref={inputRef}
          type="text"
          class="form-input"
          placeholder="Type model name..."
          disabled={props.disabled}
          value={query()}
          onInput={handleInputChange}
          onFocus={handleFocus}
          onBlur={handleBlur}
        />
        <Show when={showDropdown() && suggestions().length > 0}>
          <div
            class="absolute top-full left-0 right-0 mt-1 bg-[#1a1a1a] border border-dark-surface3 rounded-lg shadow-lg z-[100] max-h-48 overflow-y-auto"
            onMouseDown={handleMouseDown}
            onMouseUp={handleMouseUp}
          >
            <For each={suggestions()}>
              {(suggestion) => (
                <div
                  class="px-3 py-2 text-sm cursor-pointer hover:bg-accent-primary/10"
                  onClick={() => handleSelect(suggestion.value)}
                >
                  <div class="font-medium">{suggestion.label}</div>
                  <Show when={suggestion.providerName && suggestion.providerName !== 'default'}>
                    <div class="text-xs text-dark-text-muted">
                      {suggestion.providerName}
                    </div>
                  </Show>
                </div>
              )}
            </For>
          </div>
        </Show>
      </div>
    </div>
  )
}
