// src/kanban-vue/src/components/common/ToastContainer.vue
<script setup lang="ts">
const props = defineProps<{
  toasts: { id: number; message: string; variant: 'info' | 'success' | 'error' }[]
  bottomOffset: number
}>()

const emit = defineEmits<{
  remove: [id: number]
}>()

const variantClasses: Record<string, string> = {
  info: 'bg-accent-primary text-white',
  success: 'bg-accent-success text-white',
  error: 'bg-accent-danger text-white',
}
</script>

<template>
  <div
    class="fixed right-4 z-50 flex flex-col gap-2"
    :style="{ bottom: bottomOffset + 'px' }"
  >
    <TransitionGroup name="toast">
      <div
        v-for="toast in toasts"
        :key="toast.id"
        :class="[
          'px-4 py-2.5 rounded-lg text-sm shadow-lg cursor-pointer',
          variantClasses[toast.variant]
        ]"
        @click="emit('remove', toast.id)"
      >
        {{ toast.message }}
      </div>
    </TransitionGroup>
  </div>
</template>

<style scoped>
.toast-enter-active,
.toast-leave-active {
  transition: all 0.3s ease;
}

.toast-enter-from,
.toast-leave-to {
  transform: translateX(100%);
  opacity: 0;
}
</style>

// src/kanban-react/src/components/common/ToastContainer.tsx
import type { Toast } from '@/types'

interface ToastContainerProps {
  toasts: Toast[]
  bottomOffset: number
  onRemove: (id: number) => void
}

export function ToastContainer({ toasts, bottomOffset, onRemove }: ToastContainerProps) {
  return (
    <div 
      className="fixed right-4 z-50 flex flex-col gap-2"
      style={{ bottom: bottomOffset }}
    >
      {toasts.map(toast => (
        <div
          key={toast.id}
          className={`px-4 py-3 rounded-lg shadow-lg border transition-all animate-slide-in ${
            toast.variant === 'error' ? 'bg-accent-danger/20 border-accent-danger text-accent-danger' :
            toast.variant === 'success' ? 'bg-accent-success/20 border-accent-success text-accent-success' :
            'bg-dark-surface2 border-dark-border text-dark-text'
          }`}
        >
          <div className="flex items-center justify-between gap-4">
            <span className="text-sm">{toast.message}</span>
            <button
              className="text-dark-text-muted hover:text-dark-text"
              onClick={() => onRemove(toast.id)}
            >
              ×
            </button>
          </div>
        </div>
      ))}
    </div>
  )
}
