// src/kanban-react/src/components/modals/SessionModal.tsx
import { useState, useEffect } from 'react'
import { ModalWrapper } from '../common/ModalWrapper'
import { useSessionContext, useToastContext } from '@/contexts/AppContext'
import type { SessionMessage } from '@/types'

interface SessionModalProps {
  sessionId: string
  onClose: () => void
}

export function SessionModal({ sessionId, onClose }: SessionModalProps) {
  const sessionCtx = useSessionContext()
  const toasts = useToastContext()
  const [messages, setMessages] = useState<SessionMessage[]>([])
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    const loadData = async () => {
      setIsLoading(true)
      try {
        await sessionCtx.loadSession(sessionId)
      } catch (e) {
        toasts.showToast('Failed to load session', 'error')
      } finally {
        setIsLoading(false)
      }
    }
    loadData()
  }, [sessionId])

  useEffect(() => {
    setMessages(sessionCtx.messages)
  }, [sessionCtx.messages])

  return (
    <ModalWrapper title={`Session: ${sessionId.slice(0, 16)}...`} onClose={onClose} size="lg">
      <div className="space-y-4 max-h-[60vh] overflow-y-auto">
        {isLoading ? (
          <div className="text-center py-8 text-dark-text-muted">Loading session...</div>
        ) : messages.length === 0 ? (
          <div className="text-center py-8 text-dark-text-muted">No messages in this session.</div>
        ) : (
          messages.map((msg, i) => (
            <div key={msg.id || i} className="session-entry">
              <div className="flex items-center gap-2 mb-2">
                <span className={`session-role ${msg.role}`}>{msg.role}</span>
                <span className="text-xs text-dark-text-muted">
                  {new Date(msg.timestamp).toLocaleTimeString()}
                </span>
              </div>
              <div className="text-sm text-dark-text">
                {JSON.stringify(msg.contentJson, null, 2).slice(0, 500)}
              </div>
            </div>
          ))
        )}
      </div>
    </ModalWrapper>
  )
}

// src/kanban-solid/src/components/modals/SessionModal.tsx
/**
 * SessionModal Component - Session management
 * Ported from React to SolidJS
 */

import { createMemo, createEffect, Show, For } from 'solid-js'
import { createQuery } from '@tanstack/solid-query'
import { ModalWrapper } from '@/components/common/ModalWrapper'
import { sessionsApi } from '@/api'
import { formatLocalTime } from '@/utils/date'
import type { SessionMessage } from '@/types'

interface SessionModalProps {
  sessionId: string
  onClose: () => void
}

export function SessionModal(props: SessionModalProps) {
  const messagesQuery = createQuery(() => ({
    queryKey: ['sessions', props.sessionId, 'messages'],
    queryFn: () => sessionsApi.getMessages(props.sessionId, 1000),
    staleTime: 5000,
  }))

  const messages = () => messagesQuery.data || []
  const isLoading = () => messagesQuery.isLoading
  const error = () => messagesQuery.error?.message || null

  const sortedMessages = createMemo(() => {
    return [...messages()].sort((a, b) => {
      const ta = Number(a.timestamp || 0)
      const tb = Number(b.timestamp || 0)
      if (ta !== tb) return ta - tb
      return Number(a.id || 0) - Number(b.id || 0)
    })
  })

  return (
    <ModalWrapper title={`Session: ${props.sessionId.slice(0, 16)}...`} onClose={props.onClose} size="lg">
      <div class="space-y-4 max-h-[60vh] overflow-y-auto">
        <Show when={isLoading() && messages().length === 0}>
          <div class="text-center py-8 text-dark-text-muted">Loading session...</div>
        </Show>

        <Show when={error() && !isLoading()}>
          <div class="text-center py-8 text-error">Error: {error()}</div>
        </Show>

        <Show when={!isLoading() && sortedMessages().length === 0}>
          <div class="text-center py-8 text-dark-text-muted">No messages in this session.</div>
        </Show>

        <For each={sortedMessages()}>
          {(msg, i) => (
            <div class="session-entry">
              <div class="flex items-center gap-2 mb-2">
                <span class={`session-role ${msg.role}`}>{msg.role}</span>
                <span class="text-xs text-dark-text-muted">
                  {formatLocalTime(msg.timestamp)}
                </span>
              </div>
              <div class="text-sm text-dark-text">
                {JSON.stringify(msg.contentJson, null, 2).slice(0, 500)}
              </div>
            </div>
          )}
        </For>
      </div>
    </ModalWrapper>
  )
}
