// src/kanban-react/src/components/modals/StartSingleModal.tsx
import { useState } from 'react'
import { ModalWrapper } from '../common/ModalWrapper'
import { useTasksContext, useToastContext } from '@/contexts/AppContext'

interface StartSingleModalProps {
  taskId: string
  onClose: () => void
}

export function StartSingleModal({ taskId, onClose }: StartSingleModalProps) {
  const tasks = useTasksContext()
  const toasts = useToastContext()
  const [isLoading, setIsLoading] = useState(false)

  const task = tasks.getTaskById(taskId)

  const handleStart = async () => {
    setIsLoading(true)
    try {
      await tasks.startSingleTask(taskId)
      toasts.showToast('Task started', 'success')
      onClose()
    } catch (e) {
      toasts.showToast(e instanceof Error ? e.message : 'Failed to start task', 'error')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <ModalWrapper title={`Start Task: ${task?.name || taskId}`} onClose={onClose}>
      <div className="space-y-4">
        <p className="text-dark-text-secondary">
          Start this task immediately? This will bypass the normal workflow execution queue.
        </p>

        <div className="modal-footer">
          <button type="button" className="btn" onClick={onClose} disabled={isLoading}>Cancel</button>
          <button
            type="button"
            className="btn btn-primary"
            onClick={handleStart}
            disabled={isLoading}
          >
            {isLoading ? 'Starting...' : 'Start Task'}
          </button>
        </div>
      </div>
    </ModalWrapper>
  )
}

// src/kanban-solid/src/components/modals/StartSingleModal.tsx
/**
 * StartSingleModal Component - Single task start dialog
 * Ported from React to SolidJS
 */

import { createSignal, Show } from 'solid-js'
import { ModalWrapper } from '@/components/common/ModalWrapper'
import { uiStore } from '@/stores'
import type { Task } from '@/types'

interface StartSingleModalProps {
  task?: Task
  onClose: () => void
  onConfirm: (taskId: string) => Promise<void>
}

export function StartSingleModal(props: StartSingleModalProps) {
  const [isLoading, setIsLoading] = createSignal(false)

  const taskId = () => props.task?.id

  const handleStart = async () => {
    const id = taskId()
    if (!id) return
    
    setIsLoading(true)
    try {
      await props.onConfirm(id)
      uiStore.showToast('Task started', 'success')
    } catch (e) {
      uiStore.showToast(e instanceof Error ? e.message : 'Failed to start task', 'error')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <ModalWrapper title={`Start Task: ${props.task?.name || taskId() || 'Unknown'}`} onClose={props.onClose}>
      <div class="space-y-4">
        <p class="text-dark-text-secondary">
          Start this task immediately? This will bypass the normal workflow execution queue.
        </p>

        <div class="modal-footer">
          <button type="button" class="btn" onClick={props.onClose} disabled={isLoading()}>Cancel</button>
          <button
            type="button"
            class="btn btn-primary"
            onClick={handleStart}
            disabled={isLoading()}
          >
            {isLoading() ? 'Starting...' : 'Start Task'}
          </button>
        </div>
      </div>
    </ModalWrapper>
  )
}
