// src/kanban-react/src/components/modals/TaskModal.tsx
import { useState, useEffect, useMemo, memo } from 'react'
import { ModalWrapper } from '../common/ModalWrapper'
import { ModelPicker } from '../common/ModelPicker'
import { ThinkingLevelSelect } from '../common/ThinkingLevelSelect'
import { MarkdownEditor } from '../common/MarkdownEditor'
import { HelpButton } from '../common/HelpButton'
import { useTasksContext, useOptionsContext, useModelSearchContext, useToastContext } from '@/contexts/AppContext'
import { useApi } from '@/hooks'
import type { ThinkingLevel, ExecutionStrategy, BestOfNSlot } from '@/types'

export interface TaskModalProps {
  mode: 'create' | 'edit' | 'deploy' | 'view'
  taskId?: string
  createStatus?: 'template' | 'backlog'
  seedTaskId?: string
  onClose: () => void
}

export const TaskModal = memo(function TaskModal({ mode, taskId, createStatus = 'backlog', seedTaskId, onClose }: TaskModalProps) {
  const tasks = useTasksContext()
  const optionsContext = useOptionsContext()
  const modelSearch = useModelSearchContext()
  const toasts = useToastContext()
  const api = useApi()
  const getBranches = api.getBranches
  const getContainerImages = api.getContainerImages

  const [taskSnapshot] = useState(() => {
    const existingTask = taskId ? tasks.getTaskById(taskId) : null
    const seedTask = seedTaskId ? tasks.getTaskById(seedTaskId) : null
    return {
      existingTask: existingTask ? { ...existingTask } : null,
      seedTask: seedTask ? { ...seedTask } : null,
    }
  })

  // Use snapshot as the stable source of truth for initial values
  const existingTask = taskSnapshot.existingTask
  const seedTask = taskSnapshot.seedTask

  const [name, setName] = useState(existingTask?.name || seedTask?.name || '')
  const [prompt, setPrompt] = useState(existingTask?.prompt || seedTask?.prompt || '')
  const [branch, setBranch] = useState('')
  const [planModel, setPlanModel] = useState(existingTask?.planModel || optionsContext.options?.planModel || '')
  const [executionModel, setExecutionModel] = useState(existingTask?.executionModel || optionsContext.options?.executionModel || '')
  const [thinkingLevel] = useState<ThinkingLevel>(existingTask?.thinkingLevel || optionsContext.options?.thinkingLevel || 'default')
  const [planThinkingLevel, setPlanThinkingLevel] = useState<ThinkingLevel>(existingTask?.planThinkingLevel || optionsContext.options?.planThinkingLevel || 'default')
  const [executionThinkingLevel, setExecutionThinkingLevel] = useState<ThinkingLevel>(existingTask?.executionThinkingLevel || optionsContext.options?.executionThinkingLevel || 'default')
  const [planmode, setPlanmode] = useState(existingTask?.planmode ?? false)
  const [autoApprovePlan, setAutoApprovePlan] = useState(existingTask?.autoApprovePlan ?? false)
  const [review, setReview] = useState(existingTask?.review ?? true)
  const [codeStyleReview, setCodeStyleReview] = useState(existingTask?.codeStyleReview ?? false)
  const [autoCommit, setAutoCommit] = useState(existingTask?.autoCommit ?? true)
  const [deleteWorktree, setDeleteWorktree] = useState(existingTask?.deleteWorktree ?? true)
  const [skipPermissionAsking, setSkipPermissionAsking] = useState(existingTask?.skipPermissionAsking ?? true)
  const [requirements, setRequirements] = useState<string[]>(existingTask?.requirements || seedTask?.requirements || [])
  const [executionStrategy, setExecutionStrategy] = useState<ExecutionStrategy>(existingTask?.executionStrategy || 'standard')
  const [containerImage, setContainerImage] = useState(existingTask?.containerImage || '')
  const [availableBranches, setAvailableBranches] = useState<string[]>([])
  const [availableImages, setAvailableImages] = useState<Array<{ tag: string }>>([])
  const [isLoading, setIsLoading] = useState(true)
  const [bonWorkers, setBonWorkers] = useState<BestOfNSlot[]>([])
  const [bonReviewers, setBonReviewers] = useState<BestOfNSlot[]>([])
  const [bonFinalApplierModel, setBonFinalApplierModel] = useState('')
  const [bonFinalApplierSuffix, setBonFinalApplierSuffix] = useState('')
  const [bonSelectionMode, setBonSelectionMode] = useState<'pick_best' | 'synthesize' | 'pick_or_synthesize'>('pick_best')
  const [bonMinSuccessful, setBonMinSuccessful] = useState(1)
  const [bonVerificationCmd, setBonVerificationCmd] = useState('')

  const isViewOnly = mode === 'view'
  const isDeploy = mode === 'deploy'
  const isCreate = mode === 'create'
  const isEdit = mode === 'edit'

  const showBonConfig = executionStrategy === 'best_of_n'

  useEffect(() => {
    let cancelled = false
    const loadData = async () => {
      setIsLoading(true)
      try {
        const [branchData, imageData] = await Promise.all([
          getBranches(),
          getContainerImages()
        ])
        if (cancelled) return

        setAvailableBranches(branchData.branches || [])
        setAvailableImages(imageData.images || [])

        if (taskSnapshot.existingTask?.branch) {
          setBranch(taskSnapshot.existingTask.branch)
        } else if (taskSnapshot.seedTask?.branch) {
          setBranch(taskSnapshot.seedTask.branch)
        } else if (branchData.current) {
          setBranch(branchData.current)
        } else if (branchData.branches?.[0]) {
          setBranch(branchData.branches[0])
        }

        if (taskSnapshot.existingTask?.containerImage) {
          setContainerImage(taskSnapshot.existingTask.containerImage)
        } else if (optionsContext.options?.container?.image) {
          setContainerImage(optionsContext.options.container.image)
        }

        if (taskSnapshot.existingTask?.executionStrategy === 'best_of_n' && taskSnapshot.existingTask.bestOfNConfig) {
          setBonWorkers(taskSnapshot.existingTask.bestOfNConfig.workers.map(w => ({ ...w })))
          setBonReviewers(taskSnapshot.existingTask.bestOfNConfig.reviewers.map(r => ({ ...r })))
          setBonFinalApplierModel(taskSnapshot.existingTask.bestOfNConfig.finalApplier.model)
          setBonFinalApplierSuffix(taskSnapshot.existingTask.bestOfNConfig.finalApplier.taskSuffix || '')
          setBonSelectionMode(taskSnapshot.existingTask.bestOfNConfig.selectionMode)
          setBonMinSuccessful(taskSnapshot.existingTask.bestOfNConfig.minSuccessfulWorkers)
          setBonVerificationCmd(taskSnapshot.existingTask.bestOfNConfig.verificationCommand || '')
        }
      } catch (e) {
        console.error('Failed to load data:', e)
      } finally {
        if (!cancelled) setIsLoading(false)
      }
    }
    loadData()
    return () => { cancelled = true }
  }, [getBranches, getContainerImages, taskSnapshot, optionsContext.options])

  const [tasksSnapshot] = useState(() => tasks.tasks)

  const availableRequirements = useMemo(() => {
    const stableTaskId = taskSnapshot.existingTask?.id ?? taskId
    return tasksSnapshot.filter(t => {
      if (isViewOnly) return t.id !== stableTaskId
      if (t.id === stableTaskId) return false
      if (t.status === 'backlog') return true
      if (t.status === 'done' && requirements.includes(t.id)) return true
      return false
    })
  }, [tasksSnapshot, taskId, isViewOnly, requirements, taskSnapshot.existingTask?.id])

  const addBonWorker = () => {
    setBonWorkers([...bonWorkers, { model: '', count: 1, taskSuffix: '' }])
  }

  const removeBonWorker = (index: number) => {
    setBonWorkers(bonWorkers.filter((_, i) => i !== index))
  }

  const updateBonWorker = (index: number, field: 'model' | 'count' | 'taskSuffix', value: string | number) => {
    setBonWorkers(bonWorkers.map((w, i) => i === index ? { ...w, [field]: value } : w))
  }

  const addBonReviewer = () => {
    setBonReviewers([...bonReviewers, { model: '', count: 1, taskSuffix: '' }])
  }

  const removeBonReviewer = (index: number) => {
    setBonReviewers(bonReviewers.filter((_, i) => i !== index))
  }

  const updateBonReviewer = (index: number, field: 'model' | 'count' | 'taskSuffix', value: string | number) => {
    setBonReviewers(bonReviewers.map((r, i) => i === index ? { ...r, [field]: value } : r))
  }

  const toggleRequirement = (taskId: string) => {
    setRequirements(prev =>
      prev.includes(taskId) ? prev.filter(id => id !== taskId) : [...prev, taskId]
    )
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!name.trim() || !prompt.trim()) {
      toasts.showToast('Name and prompt are required', 'error')
      return
    }

    if (!branch) {
      toasts.showToast('Select a valid branch', 'error')
      return
    }

    if (executionStrategy === 'best_of_n') {
      if (bonWorkers.length === 0) {
        toasts.showToast('Add at least one worker slot for Best of N', 'error')
        return
      }
      const totalWorkers = bonWorkers.reduce((sum, w) => sum + (w.count || 1), 0)
      if (totalWorkers > 8) {
        toasts.showToast(`Total workers (${totalWorkers}) exceeds maximum of 8`, 'error')
        return
      }
      if (bonMinSuccessful > totalWorkers) {
        toasts.showToast('Minimum successful workers cannot exceed total workers', 'error')
        return
      }
    }

    try {
      const taskData: Record<string, unknown> = {
        name: name.trim(),
        prompt: prompt.trim(),
        branch,
        planModel: modelSearch.normalizeValue(planModel),
        executionModel: modelSearch.normalizeValue(executionModel),
        planmode,
        autoApprovePlan,
        review,
        codeStyleReview,
        autoCommit,
        deleteWorktree,
        skipPermissionAsking,
        requirements,
        thinkingLevel,
        planThinkingLevel,
        executionThinkingLevel,
        executionStrategy,
        containerImage: containerImage || undefined,
      }

      if (executionStrategy === 'best_of_n') {
        taskData.bestOfNConfig = {
          workers: bonWorkers.map(w => ({
            model: w.model,
            count: w.count || 1,
            taskSuffix: w.taskSuffix || undefined,
          })),
          reviewers: bonReviewers.map(r => ({
            model: r.model,
            count: r.count || 1,
            taskSuffix: r.taskSuffix || undefined,
          })),
          finalApplier: {
            model: modelSearch.normalizeValue(bonFinalApplierModel),
            taskSuffix: bonFinalApplierSuffix.trim() || undefined,
          },
          selectionMode: bonSelectionMode,
          minSuccessfulWorkers: bonMinSuccessful,
          verificationCommand: bonVerificationCmd.trim() || undefined,
        }
      }

      if (isEdit && taskId) {
        await tasks.updateTask(taskId, taskData)
        toasts.showToast('Task updated', 'success')
      } else if (isDeploy && seedTaskId) {
        await tasks.createTask({ ...taskData, status: 'backlog' } as { name: string; prompt: string; status: 'backlog' })
        toasts.showToast('Template deployed', 'success')
      } else {
        await tasks.createTask({ ...taskData, status: createStatus } as { name: string; prompt: string; status: typeof createStatus })
        toasts.showToast('Task created', 'success')
      }
      onClose()
    } catch (e) {
      toasts.showToast(e instanceof Error ? e.message : 'Failed to save task', 'error')
    }
  }

  const getTitle = () => {
    if (isViewOnly) return 'View Task'
    if (isDeploy) return 'Deploy Template'
    if (isEdit) return createStatus === 'template' ? 'Edit Template' : 'Edit Task'
    return createStatus === 'template' ? 'Add Template' : 'Add Task'
  }

  const getSaveButtonText = () => {
    if (isDeploy) return 'Send to Backlog'
    if (isCreate && createStatus === 'template') return 'Save Template'
    return 'Save'
  }

  if (isLoading) {
    return (
      <ModalWrapper title={getTitle()} onClose={onClose} size="lg">
        <div className="p-8 text-center">
          <div className="text-dark-text-muted">Loading...</div>
        </div>
      </ModalWrapper>
    )
  }

  return (
    <ModalWrapper title={getTitle()} onClose={onClose} size="lg">
      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Name */}
        <div className="form-group">
          <div className="label-row">
            <label>Name</label>
            <HelpButton tooltip="Short task title shown on the card." />
          </div>
          <input
            type="text"
            className="form-input"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Task name"
            disabled={isViewOnly}
            required
          />
        </div>

        {/* Prompt */}
        <div className="form-group">
          <div className="label-row">
            <label>Prompt</label>
            <HelpButton tooltip="The main instructions for the agent." />
          </div>
          <MarkdownEditor
            modelValue={prompt}
            onUpdate={setPrompt}
            placeholder="What should this task do?"
            disabled={isViewOnly}
          />
        </div>

        {/* Models with Thinking Levels */}
        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-2">
            <ModelPicker
              modelValue={planModel}
              label="Plan Model"
              help="Model used for planning steps before implementation."
              disabled={isViewOnly}
              onUpdate={setPlanModel}
            />
            <ThinkingLevelSelect
              modelValue={planThinkingLevel}
              label="Plan Thinking"
              help="Thinking level for planning phase."
              disabled={isViewOnly}
              onUpdate={(v) => setPlanThinkingLevel(v as ThinkingLevel)}
            />
          </div>
          <div className="space-y-2">
            <ModelPicker
              modelValue={executionModel}
              label="Execution Model"
              help="Model used for the actual implementation work."
              disabled={isViewOnly}
              onUpdate={setExecutionModel}
            />
            <ThinkingLevelSelect
              modelValue={executionThinkingLevel}
              label="Execution Thinking"
              help="Thinking level for execution phase."
              disabled={isViewOnly}
              onUpdate={(v) => setExecutionThinkingLevel(v as ThinkingLevel)}
            />
          </div>
        </div>

        {/* Execution Strategy */}
        <div className="form-group">
          <div className="label-row">
            <label>Execution Strategy</label>
            <HelpButton tooltip="Standard runs a single execution. Best of N runs multiple candidates in parallel and picks or synthesizes the best result." />
          </div>
          <select
            className="form-select"
            value={executionStrategy}
            onChange={(e) => setExecutionStrategy(e.target.value as ExecutionStrategy)}
            disabled={isViewOnly}
          >
            <option value="standard">Standard</option>
            <option value="best_of_n">Best of N</option>
          </select>
        </div>

        {/* Container Image */}
        <div className="form-group">
          <div className="label-row">
            <label>Container Image</label>
            <HelpButton tooltip="Select the container image for this task. Uses system default if not specified." />
          </div>
          <select
            className="form-select"
            value={containerImage}
            onChange={(e) => setContainerImage(e.target.value)}
            disabled={isViewOnly}
          >
            <option value="">System Default</option>
            {availableImages.map(img => (
              <option key={img.tag} value={img.tag}>{img.tag}</option>
            ))}
          </select>
          {availableImages.length > 0 && (
            <div className="text-xs text-dark-text-muted mt-1">Build custom images in the Image Builder</div>
          )}
        </div>

        {/* Best-of-N Config */}
        {showBonConfig && (
          <div className="border border-dark-surface3 rounded-lg p-3 bg-dark-bg">
            <h4 className="text-sm font-semibold mb-2">Best of N Configuration</h4>

            {/* Workers */}
            <div className="form-group">
              <label>Workers</label>
              <div className="space-y-2">
                {bonWorkers.map((slot, i) => (
                  <div key={i} className="flex gap-2 items-center">
                    <input
                      type="number"
                      min={1}
                      max={4}
                      className="form-input w-16"
                      value={slot.count || 1}
                      onChange={(e) => updateBonWorker(i, 'count', parseInt(e.target.value) || 1)}
                      disabled={isViewOnly}
                    />
                    <select
                      className="form-select flex-1"
                      value={slot.model}
                      onChange={(e) => updateBonWorker(i, 'model', e.target.value)}
                      disabled={isViewOnly}
                    >
                      <option value="">Select model...</option>
                      {modelSearch.getModelOptions(slot.model).map(opt => (
                        <option key={opt.value} value={opt.value}>{opt.label}</option>
                      ))}
                    </select>
                    <input
                      type="text"
                      placeholder="Suffix (optional)"
                      className="form-input flex-1"
                      value={slot.taskSuffix || ''}
                      onChange={(e) => updateBonWorker(i, 'taskSuffix', e.target.value)}
                      disabled={isViewOnly}
                    />
                    {!isViewOnly && (
                      <button
                        type="button"
                        className="text-red-400 hover:text-red-300 px-2"
                        onClick={() => removeBonWorker(i)}
                      >
                        ✕
                      </button>
                    )}
                  </div>
                ))}
              </div>
              {!isViewOnly && (
                <button type="button" className="add-task-btn mt-2" onClick={addBonWorker}>
                  + Add Worker Slot
                </button>
              )}
            </div>

            {/* Reviewers */}
            <div className="form-group">
              <label>Reviewers</label>
              <div className="space-y-2">
                {bonReviewers.map((slot, i) => (
                  <div key={i} className="flex gap-2 items-center">
                    <input
                      type="number"
                      min={1}
                      max={4}
                      className="form-input w-16"
                      value={slot.count || 1}
                      onChange={(e) => updateBonReviewer(i, 'count', parseInt(e.target.value) || 1)}
                      disabled={isViewOnly}
                    />
                    <select
                      className="form-select flex-1"
                      value={slot.model}
                      onChange={(e) => updateBonReviewer(i, 'model', e.target.value)}
                      disabled={isViewOnly}
                    >
                      <option value="">Select model...</option>
                      {modelSearch.getModelOptions(slot.model).map(opt => (
                        <option key={opt.value} value={opt.value}>{opt.label}</option>
                      ))}
                    </select>
                    <input
                      type="text"
                      placeholder="Suffix (optional)"
                      className="form-input flex-1"
                      value={slot.taskSuffix || ''}
                      onChange={(e) => updateBonReviewer(i, 'taskSuffix', e.target.value)}
                      disabled={isViewOnly}
                    />
                    {!isViewOnly && (
                      <button
                        type="button"
                        className="text-red-400 hover:text-red-300 px-2"
                        onClick={() => removeBonReviewer(i)}
                      >
                        ✕
                      </button>
                    )}
                  </div>
                ))}
              </div>
              {!isViewOnly && (
                <button type="button" className="add-task-btn mt-2" onClick={addBonReviewer}>
                  + Add Reviewer Slot
                </button>
              )}
            </div>

            {/* Final Applier */}
            <ModelPicker
              modelValue={bonFinalApplierModel}
              label="Final Applier Model"
              disabled={isViewOnly}
              onUpdate={setBonFinalApplierModel}
            />

            <div className="form-group">
              <label>Final Applier Suffix (optional)</label>
              <textarea
                className="form-textarea"
                placeholder="Additional instructions for the final applier..."
                value={bonFinalApplierSuffix}
                onChange={(e) => setBonFinalApplierSuffix(e.target.value)}
                disabled={isViewOnly}
              />
            </div>

            {/* Selection Mode & Min Successful */}
            <div className="grid grid-cols-2 gap-3">
              <div className="form-group">
                <label>Selection Mode</label>
                <select
                  className="form-select"
                  value={bonSelectionMode}
                  onChange={(e) => setBonSelectionMode(e.target.value as typeof bonSelectionMode)}
                  disabled={isViewOnly}
                >
                  <option value="pick_best">Pick Best</option>
                  <option value="synthesize">Synthesize</option>
                  <option value="pick_or_synthesize">Pick or Synthesize</option>
                </select>
              </div>
              <div className="form-group">
                <label>Min Successful Workers</label>
                <input
                  type="number"
                  min={1}
                  max={8}
                  className="form-input"
                  value={bonMinSuccessful}
                  onChange={(e) => setBonMinSuccessful(parseInt(e.target.value) || 1)}
                  disabled={isViewOnly}
                />
              </div>
            </div>

            {/* Verification Command */}
            <div className="form-group">
              <label>Verification Command (optional)</label>
              <input
                type="text"
                className="form-input"
                placeholder="e.g. npm test"
                value={bonVerificationCmd}
                onChange={(e) => setBonVerificationCmd(e.target.value)}
                disabled={isViewOnly}
              />
            </div>
          </div>
        )}

        {/* Branch */}
        <div className="form-group">
          <div className="label-row">
            <label>Branch</label>
            <HelpButton tooltip="Git branch the task should run against." />
          </div>
          <select
            className="form-select"
            value={branch}
            onChange={(e) => setBranch(e.target.value)}
            disabled={isViewOnly}
          >
            {availableBranches.map(b => (
              <option key={b} value={b}>{b}</option>
            ))}
          </select>
        </div>

        {/* Checkboxes */}
        {!isViewOnly && (
          <div className="checkbox-group">
            <label className="checkbox-item">
              <input type="checkbox" checked={planmode} onChange={(e) => setPlanmode(e.target.checked)} />
              <span>Plan Mode</span>
            </label>
            <label className="checkbox-item">
              <input type="checkbox" checked={autoApprovePlan} onChange={(e) => setAutoApprovePlan(e.target.checked)} />
              <span>Auto-approve plan</span>
            </label>
            <label className="checkbox-item">
              <input type="checkbox" checked={review} onChange={(e) => setReview(e.target.checked)} />
              <span>Review</span>
            </label>
            <label className="checkbox-item">
              <input
                type="checkbox"
                checked={codeStyleReview}
                onChange={(e) => setCodeStyleReview(e.target.checked)}
                disabled={!review}
              />
              <span className={!review ? 'opacity-50' : ''}>Code Style Review (after review)</span>
            </label>
            <label className="checkbox-item">
              <input type="checkbox" checked={autoCommit} onChange={(e) => setAutoCommit(e.target.checked)} />
              <span>Auto-commit</span>
            </label>
            <label className="checkbox-item">
              <input type="checkbox" checked={deleteWorktree} onChange={(e) => setDeleteWorktree(e.target.checked)} />
              <span>Delete Worktree</span>
            </label>
            <label className="checkbox-item">
              <input type="checkbox" checked={skipPermissionAsking} onChange={(e) => setSkipPermissionAsking(e.target.checked)} />
              <span>Skip Permission Asking</span>
            </label>
          </div>
        )}

        {/* Requirements */}
        <div className="form-group">
          <div className="label-row">
            <label>Requirements (dependencies)</label>
            <HelpButton tooltip="Tasks that must be completed before this one should run." />
          </div>
          <div className="border border-dark-surface3 rounded-lg p-1.5 max-h-36 overflow-y-auto">
            {availableRequirements.map(t => (
              <label
                key={t.id}
                className="checkbox-item p-1 rounded hover:bg-dark-surface2"
              >
                <input
                  type="checkbox"
                  checked={requirements.includes(t.id)}
                  onChange={() => toggleRequirement(t.id)}
                  disabled={isViewOnly}
                />
                <span className="text-sm">{t.name} (#{t.idx + 1})</span>
              </label>
            ))}
            {availableRequirements.length === 0 && (
              <div className="text-xs text-dark-text-muted p-1">No other tasks</div>
            )}
          </div>
        </div>

        <div className="modal-footer">
          <button type="button" className="btn" onClick={onClose}>Cancel</button>
          {!isViewOnly && (
            <button type="submit" className="btn btn-primary">
              {getSaveButtonText()}
            </button>
          )}
        </div>
      </form>
    </ModalWrapper>
  )
})

// src/kanban-solid/src/components/modals/TaskModal.tsx
/**
 * TaskModal Component - Create/edit/deploy task modal
 * Ported from React to SolidJS
 */

import { createSignal, createEffect, createMemo, onMount, Show, For, batch } from 'solid-js'
import type { Task, TaskStatus, CreateTaskDTO, ThinkingLevel, ExecutionStrategy, BestOfNSlot } from '@/types'
import { ModalWrapper } from '../common/ModalWrapper'
import { ModelPicker } from '../common/ModelPicker'
import { ThinkingLevelSelect } from '../common/ThinkingLevelSelect'
import { MarkdownEditor } from '../common/MarkdownEditor'
import { HelpButton } from '../common/HelpButton'
import { createTasksStore, createOptionsStore, createModelSearchStore, uiStore } from '@/stores'
import { referenceApi, containersApi } from '@/api'

export type TaskModalMode = 'create' | 'edit' | 'deploy' | 'view'

interface TaskModalProps {
  mode: TaskModalMode
  taskId?: string
  createStatus?: TaskStatus
  seedTaskId?: string
  onClose: () => void
}

export function TaskModal(props: TaskModalProps) {
  // Initialize stores
  const tasksStore = createTasksStore()
  const optionsStore = createOptionsStore()
  const modelSearch = createModelSearchStore()

  // Create a stable snapshot of the task data (stable reference like React's useState initializer)
  const [taskSnapshot] = createSignal((() => {
    const existingTask = props.taskId ? tasksStore.getTaskById(props.taskId) : null
    const seedTask = props.seedTaskId ? tasksStore.getTaskById(props.seedTaskId) : null
    return {
      existingTask: existingTask ? { ...existingTask } : null,
      seedTask: seedTask ? { ...seedTask } : null,
    }
  })())

  // Use snapshot as the stable source of truth for initial values
  const existingTask = () => taskSnapshot().existingTask
  const seedTask = () => taskSnapshot().seedTask

  // Form state
  const [name, setName] = createSignal(existingTask()?.name || seedTask()?.name || '')
  const [prompt, setPrompt] = createSignal(existingTask()?.prompt || seedTask()?.prompt || '')
  const [branch, setBranch] = createSignal('')
  const [planModel, setPlanModel] = createSignal(existingTask()?.planModel || optionsStore.options()?.planModel || '')
  const [executionModel, setExecutionModel] = createSignal(existingTask()?.executionModel || optionsStore.options()?.executionModel || '')
  const [planThinkingLevel, setPlanThinkingLevel] = createSignal<ThinkingLevel>(existingTask()?.planThinkingLevel || optionsStore.options()?.planThinkingLevel || 'default')
  const [executionThinkingLevel, setExecutionThinkingLevel] = createSignal<ThinkingLevel>(existingTask()?.executionThinkingLevel || optionsStore.options()?.executionThinkingLevel || 'default')
  const [planmode, setPlanmode] = createSignal(existingTask()?.planmode ?? false)
  const [autoApprovePlan, setAutoApprovePlan] = createSignal(existingTask()?.autoApprovePlan ?? false)
  const [review, setReview] = createSignal(existingTask()?.review ?? true)
  const [codeStyleReview, setCodeStyleReview] = createSignal(existingTask()?.codeStyleReview ?? false)
  const [autoCommit, setAutoCommit] = createSignal(existingTask()?.autoCommit ?? true)
  const [deleteWorktree, setDeleteWorktree] = createSignal(existingTask()?.deleteWorktree ?? true)
  const [skipPermissionAsking, setSkipPermissionAsking] = createSignal(existingTask()?.skipPermissionAsking ?? true)
  const [requirements, setRequirements] = createSignal<string[]>(existingTask()?.requirements || seedTask()?.requirements || [])
  const [executionStrategy, setExecutionStrategy] = createSignal<ExecutionStrategy>(existingTask()?.executionStrategy || 'standard')
  const [containerImage, setContainerImage] = createSignal(existingTask()?.containerImage || '')
  const [availableBranches, setAvailableBranches] = createSignal<string[]>([])
  const [availableImages, setAvailableImages] = createSignal<Array<{ tag: string }>>([])
  const [isLoading, setIsLoading] = createSignal(true)
  
  // Best-of-N state
  const [bonWorkers, setBonWorkers] = createSignal<BestOfNSlot[]>([])
  const [bonReviewers, setBonReviewers] = createSignal<BestOfNSlot[]>([])
  const [bonFinalApplierModel, setBonFinalApplierModel] = createSignal('')
  const [bonFinalApplierSuffix, setBonFinalApplierSuffix] = createSignal('')
  const [bonSelectionMode, setBonSelectionMode] = createSignal<'pick_best' | 'synthesize' | 'pick_or_synthesize'>('pick_best')
  const [bonMinSuccessful, setBonMinSuccessful] = createSignal(1)
  const [bonVerificationCmd, setBonVerificationCmd] = createSignal('')

  // Computed values
  const isViewOnly = () => props.mode === 'view'
  const isDeploy = () => props.mode === 'deploy'
  const isCreate = () => props.mode === 'create'
  const isEdit = () => props.mode === 'edit'
  const showBonConfig = () => executionStrategy() === 'best_of_n'

  // Load data on mount
  onMount(async () => {
    setIsLoading(true)
    try {
      const [branchData, imageData] = await Promise.all([
        referenceApi.getBranches(),
        containersApi.getImages()
      ])

      setAvailableBranches(branchData.branches || [])
      setAvailableImages(imageData.images || [])

      // Set branch
      if (existingTask()?.branch) {
        setBranch(existingTask()!.branch)
      } else if (seedTask()?.branch) {
        setBranch(seedTask()!.branch)
      } else if (branchData.current) {
        setBranch(branchData.current)
      } else if (branchData.branches?.[0]) {
        setBranch(branchData.branches[0])
      }

      // Set container image
      if (existingTask()?.containerImage) {
        setContainerImage(existingTask()!.containerImage)
      } else if (optionsStore.options()?.container?.image) {
        setContainerImage(optionsStore.options()!.container.image)
      }

      // Load Best-of-N config if present
      if (existingTask()?.executionStrategy === 'best_of_n' && existingTask()?.bestOfNConfig) {
        const config = existingTask()!.bestOfNConfig!
        setBonWorkers(config.workers.map(w => ({ ...w })))
        setBonReviewers(config.reviewers.map(r => ({ ...r })))
        setBonFinalApplierModel(config.finalApplier.model)
        setBonFinalApplierSuffix(config.finalApplier.taskSuffix || '')
        setBonSelectionMode(config.selectionMode)
        setBonMinSuccessful(config.minSuccessfulWorkers)
        setBonVerificationCmd(config.verificationCommand || '')
      }
    } catch (e) {
      console.error('Failed to load data:', e)
      uiStore.showToast('Failed to load form data', 'error')
    } finally {
      setIsLoading(false)
    }
  })

  // Get tasks snapshot for requirements (stable reference)
  const [tasksSnapshot] = createSignal(tasksStore.tasks())

  const availableRequirements = createMemo(() => {
    const stableTaskId = existingTask()?.id ?? props.taskId
    return tasksSnapshot().filter(t => {
      if (isViewOnly()) return t.id !== stableTaskId
      if (t.id === stableTaskId) return false
      if (t.status === 'backlog') return true
      if (t.status === 'done' && requirements().includes(t.id)) return true
      return false
    })
  })

  // Best-of-N handlers
  const addBonWorker = () => {
    setBonWorkers([...bonWorkers(), { model: '', count: 1, taskSuffix: '' }])
  }

  const removeBonWorker = (index: number) => {
    setBonWorkers(bonWorkers().filter((_, i) => i !== index))
  }

  const updateBonWorker = (index: number, field: 'model' | 'count' | 'taskSuffix', value: string | number) => {
    setBonWorkers(bonWorkers().map((w, i) => i === index ? { ...w, [field]: value } : w))
  }

  const addBonReviewer = () => {
    setBonReviewers([...bonReviewers(), { model: '', count: 1, taskSuffix: '' }])
  }

  const removeBonReviewer = (index: number) => {
    setBonReviewers(bonReviewers().filter((_, i) => i !== index))
  }

  const updateBonReviewer = (index: number, field: 'model' | 'count' | 'taskSuffix', value: string | number) => {
    setBonReviewers(bonReviewers().map((r, i) => i === index ? { ...r, [field]: value } : r))
  }

  const toggleRequirement = (taskId: string) => {
    setRequirements(prev =>
      prev.includes(taskId) ? prev.filter(id => id !== taskId) : [...prev, taskId]
    )
  }

  const handleSubmit = async (e: Event) => {
    e.preventDefault()

    if (!name().trim() || !prompt().trim()) {
      uiStore.showToast('Name and prompt are required', 'error')
      return
    }

    if (!branch()) {
      uiStore.showToast('Select a valid branch', 'error')
      return
    }

    if (executionStrategy() === 'best_of_n') {
      if (bonWorkers().length === 0) {
        uiStore.showToast('Add at least one worker slot for Best of N', 'error')
        return
      }
      const totalWorkers = bonWorkers().reduce((sum, w) => sum + (w.count || 1), 0)
      if (totalWorkers > 8) {
        uiStore.showToast(`Total workers (${totalWorkers}) exceeds maximum of 8`, 'error')
        return
      }
      if (bonMinSuccessful() > totalWorkers) {
        uiStore.showToast('Minimum successful workers cannot exceed total workers', 'error')
        return
      }
    }

    try {
      const taskData: Record<string, unknown> = {
        name: name().trim(),
        prompt: prompt().trim(),
        branch: branch(),
        planModel: modelSearch.normalizeValue(planModel()),
        executionModel: modelSearch.normalizeValue(executionModel()),
        planmode: planmode(),
        autoApprovePlan: autoApprovePlan(),
        review: review(),
        codeStyleReview: codeStyleReview(),
        autoCommit: autoCommit(),
        deleteWorktree: deleteWorktree(),
        skipPermissionAsking: skipPermissionAsking(),
        requirements: requirements(),
        planThinkingLevel: planThinkingLevel(),
        executionThinkingLevel: executionThinkingLevel(),
        executionStrategy: executionStrategy(),
        containerImage: containerImage() || undefined,
      }

      if (executionStrategy() === 'best_of_n') {
        taskData.bestOfNConfig = {
          workers: bonWorkers().map(w => ({
            model: w.model,
            count: w.count || 1,
            taskSuffix: w.taskSuffix || undefined,
          })),
          reviewers: bonReviewers().map(r => ({
            model: r.model,
            count: r.count || 1,
            taskSuffix: r.taskSuffix || undefined,
          })),
          finalApplier: {
            model: modelSearch.normalizeValue(bonFinalApplierModel()),
            taskSuffix: bonFinalApplierSuffix().trim() || undefined,
          },
          selectionMode: bonSelectionMode(),
          minSuccessfulWorkers: bonMinSuccessful(),
          verificationCommand: bonVerificationCmd().trim() || undefined,
        }
      }

      if (isEdit() && props.taskId) {
        await tasksStore.updateTask(props.taskId, taskData)
        uiStore.showToast('Task updated', 'success')
      } else if (isDeploy() && props.seedTaskId) {
        await tasksStore.createTask({ ...taskData, status: 'backlog' } as CreateTaskDTO)
        uiStore.showToast('Template deployed', 'success')
      } else {
        await tasksStore.createTask({ ...taskData, status: props.createStatus || 'backlog' } as CreateTaskDTO)
        uiStore.showToast('Task created', 'success')
      }
      props.onClose()
    } catch (e) {
      uiStore.showToast(e instanceof Error ? e.message : 'Failed to save task', 'error')
    }
  }

  const getTitle = () => {
    if (isViewOnly()) return 'View Task'
    if (isDeploy()) return 'Deploy Template'
    if (isEdit()) return props.createStatus === 'template' ? 'Edit Template' : 'Edit Task'
    return props.createStatus === 'template' ? 'Add Template' : 'Add Task'
  }

  const getSaveButtonText = () => {
    if (isDeploy()) return 'Send to Backlog'
    if (isCreate() && props.createStatus === 'template') return 'Save Template'
    return 'Save'
  }

  return (
    <ModalWrapper title={getTitle()} onClose={props.onClose} size="lg">
      <Show when={isLoading()}>
        <div class="p-8 text-center">
          <div class="text-dark-text-muted">Loading...</div>
        </div>
      </Show>

      <Show when={!isLoading()}>
        <form onSubmit={handleSubmit} class="space-y-4">
          {/* Name */}
          <div class="form-group">
            <div class="label-row">
              <label>Name</label>
              <HelpButton tooltip="Short task title shown on the card." />
            </div>
            <input
              type="text"
              class="form-input"
              value={name()}
              onInput={(e) => setName(e.currentTarget.value)}
              placeholder="Task name"
              disabled={isViewOnly()}
              required
            />
          </div>

          {/* Prompt */}
          <div class="form-group">
            <div class="label-row">
              <label>Prompt</label>
              <HelpButton tooltip="The main instructions for the agent." />
            </div>
            <MarkdownEditor
              modelValue={prompt()}
              onUpdate={setPrompt}
              placeholder="What should this task do?"
              disabled={isViewOnly()}
            />
          </div>

          {/* Models with Thinking Levels */}
          <div class="grid grid-cols-2 gap-3">
            <div class="space-y-2">
              <ModelPicker
                modelValue={planModel()}
                label="Plan Model"
                help="Model used for planning steps before implementation."
                disabled={isViewOnly()}
                onUpdate={setPlanModel}
              />
              <ThinkingLevelSelect
                modelValue={planThinkingLevel()}
                label="Plan Thinking"
                help="Thinking level for planning phase."
                disabled={isViewOnly()}
                onUpdate={(v) => setPlanThinkingLevel(v as ThinkingLevel)}
              />
            </div>
            <div class="space-y-2">
              <ModelPicker
                modelValue={executionModel()}
                label="Execution Model"
                help="Model used for the actual implementation work."
                disabled={isViewOnly()}
                onUpdate={setExecutionModel}
              />
              <ThinkingLevelSelect
                modelValue={executionThinkingLevel()}
                label="Execution Thinking"
                help="Thinking level for execution phase."
                disabled={isViewOnly()}
                onUpdate={(v) => setExecutionThinkingLevel(v as ThinkingLevel)}
              />
            </div>
          </div>

          {/* Execution Strategy */}
          <div class="form-group">
            <div class="label-row">
              <label>Execution Strategy</label>
              <HelpButton tooltip="Standard runs a single execution. Best of N runs multiple candidates in parallel and picks or synthesizes the best result." />
            </div>
            <select
              class="form-select"
              value={executionStrategy()}
              onChange={(e) => setExecutionStrategy(e.currentTarget.value as ExecutionStrategy)}
              disabled={isViewOnly()}
            >
              <option value="standard">Standard</option>
              <option value="best_of_n">Best of N</option>
            </select>
          </div>

          {/* Container Image */}
          <div class="form-group">
            <div class="label-row">
              <label>Container Image</label>
              <HelpButton tooltip="Select the container image for this task. Uses system default if not specified." />
            </div>
            <select
              class="form-select"
              value={containerImage()}
              onChange={(e) => setContainerImage(e.currentTarget.value)}
              disabled={isViewOnly()}
            >
              <option value="">System Default</option>
              <For each={availableImages()}>
                {(img) => <option value={img.tag}>{img.tag}</option>}
              </For>
            </select>
            <Show when={availableImages().length > 0}>
              <div class="text-xs text-dark-text-muted mt-1">Build custom images in the Image Builder</div>
            </Show>
          </div>

          {/* Best-of-N Config */}
          <Show when={showBonConfig()}>
            <div class="border border-dark-surface3 rounded-lg p-3 bg-dark-bg">
              <h4 class="text-sm font-semibold mb-2">Best of N Configuration</h4>

              {/* Workers */}
              <div class="form-group">
                <label>Workers</label>
                <div class="space-y-2">
                  <For each={bonWorkers()}>
                    {(slot, i) => (
                      <div class="flex gap-2 items-center">
                        <input
                          type="number"
                          min={1}
                          max={4}
                          class="form-input w-16"
                          value={slot.count || 1}
                          onChange={(e) => updateBonWorker(i(), 'count', parseInt(e.currentTarget.value) || 1)}
                          disabled={isViewOnly()}
                        />
                        <select
                          class="form-select flex-1"
                          value={slot.model}
                          onChange={(e) => updateBonWorker(i(), 'model', e.currentTarget.value)}
                          disabled={isViewOnly()}
                        >
                          <option value="">Select model...</option>
                          <For each={modelSearch.getModelOptions(slot.model)}>
                            {(opt) => <option value={opt.value}>{opt.label}</option>}
                          </For>
                        </select>
                        <input
                          type="text"
                          placeholder="Suffix (optional)"
                          class="form-input flex-1"
                          value={slot.taskSuffix || ''}
                          onChange={(e) => updateBonWorker(i(), 'taskSuffix', e.currentTarget.value)}
                          disabled={isViewOnly()}
                        />
                        <Show when={!isViewOnly()}>
                          <button
                            type="button"
                            class="text-red-400 hover:text-red-300 px-2"
                            onClick={() => removeBonWorker(i())}
                          >
                            ✕
                          </button>
                        </Show>
                      </div>
                    )}
                  </For>
                </div>
                <Show when={!isViewOnly()}>
                  <button type="button" class="add-task-btn mt-2" onClick={addBonWorker}>
                    + Add Worker Slot
                  </button>
                </Show>
              </div>

              {/* Reviewers */}
              <div class="form-group">
                <label>Reviewers</label>
                <div class="space-y-2">
                  <For each={bonReviewers()}>
                    {(slot, i) => (
                      <div class="flex gap-2 items-center">
                        <input
                          type="number"
                          min={1}
                          max={4}
                          class="form-input w-16"
                          value={slot.count || 1}
                          onChange={(e) => updateBonReviewer(i(), 'count', parseInt(e.currentTarget.value) || 1)}
                          disabled={isViewOnly()}
                        />
                        <select
                          class="form-select flex-1"
                          value={slot.model}
                          onChange={(e) => updateBonReviewer(i(), 'model', e.currentTarget.value)}
                          disabled={isViewOnly()}
                        >
                          <option value="">Select model...</option>
                          <For each={modelSearch.getModelOptions(slot.model)}>
                            {(opt) => <option value={opt.value}>{opt.label}</option>}
                          </For>
                        </select>
                        <input
                          type="text"
                          placeholder="Suffix (optional)"
                          class="form-input flex-1"
                          value={slot.taskSuffix || ''}
                          onChange={(e) => updateBonReviewer(i(), 'taskSuffix', e.currentTarget.value)}
                          disabled={isViewOnly()}
                        />
                        <Show when={!isViewOnly()}>
                          <button
                            type="button"
                            class="text-red-400 hover:text-red-300 px-2"
                            onClick={() => removeBonReviewer(i())}
                          >
                            ✕
                          </button>
                        </Show>
                      </div>
                    )}
                  </For>
                </div>
                <Show when={!isViewOnly()}>
                  <button type="button" class="add-task-btn mt-2" onClick={addBonReviewer}>
                    + Add Reviewer Slot
                  </button>
                </Show>
              </div>

              {/* Final Applier */}
              <ModelPicker
                modelValue={bonFinalApplierModel()}
                label="Final Applier Model"
                disabled={isViewOnly()}
                onUpdate={setBonFinalApplierModel}
              />

              <div class="form-group">
                <label>Final Applier Suffix (optional)</label>
                <textarea
                  class="form-textarea"
                  placeholder="Additional instructions for the final applier..."
                  value={bonFinalApplierSuffix()}
                  onChange={(e) => setBonFinalApplierSuffix(e.currentTarget.value)}
                  disabled={isViewOnly()}
                />
              </div>

              {/* Selection Mode & Min Successful */}
              <div class="grid grid-cols-2 gap-3">
                <div class="form-group">
                  <label>Selection Mode</label>
                  <select
                    class="form-select"
                    value={bonSelectionMode()}
                    onChange={(e) => setBonSelectionMode(e.currentTarget.value as 'pick_best' | 'synthesize' | 'pick_or_synthesize')}
                    disabled={isViewOnly()}
                  >
                    <option value="pick_best">Pick Best</option>
                    <option value="synthesize">Synthesize</option>
                    <option value="pick_or_synthesize">Pick or Synthesize</option>
                  </select>
                </div>
                <div class="form-group">
                  <label>Min Successful Workers</label>
                  <input
                    type="number"
                    min={1}
                    max={8}
                    class="form-input"
                    value={bonMinSuccessful()}
                    onChange={(e) => setBonMinSuccessful(parseInt(e.currentTarget.value) || 1)}
                    disabled={isViewOnly()}
                  />
                </div>
              </div>

              {/* Verification Command */}
              <div class="form-group">
                <label>Verification Command (optional)</label>
                <input
                  type="text"
                  class="form-input"
                  placeholder="e.g. npm test"
                  value={bonVerificationCmd()}
                  onChange={(e) => setBonVerificationCmd(e.currentTarget.value)}
                  disabled={isViewOnly()}
                />
              </div>
            </div>
          </Show>

          {/* Branch */}
          <div class="form-group">
            <div class="label-row">
              <label>Branch</label>
              <HelpButton tooltip="Git branch the task should run against." />
            </div>
            <select
              class="form-select"
              value={branch()}
              onChange={(e) => setBranch(e.currentTarget.value)}
              disabled={isViewOnly()}
            >
              <For each={availableBranches()}>
                {(b) => <option value={b}>{b}</option>}
              </For>
            </select>
          </div>

          {/* Checkboxes */}
          <Show when={!isViewOnly()}>
            <div class="checkbox-group">
              <label class="checkbox-item">
                <input 
                  type="checkbox" 
                  checked={planmode()} 
                  onChange={(e) => setPlanmode(e.currentTarget.checked)} 
                />
                <span>Plan Mode</span>
              </label>
              <label class="checkbox-item">
                <input 
                  type="checkbox" 
                  checked={autoApprovePlan()} 
                  onChange={(e) => setAutoApprovePlan(e.currentTarget.checked)} 
                />
                <span>Auto-approve plan</span>
              </label>
              <label class="checkbox-item">
                <input 
                  type="checkbox" 
                  checked={review()} 
                  onChange={(e) => setReview(e.currentTarget.checked)} 
                />
                <span>Review</span>
              </label>
              <label class="checkbox-item">
                <input
                  type="checkbox"
                  checked={codeStyleReview()}
                  onChange={(e) => setCodeStyleReview(e.currentTarget.checked)}
                  disabled={!review()}
                />
                <span class={!review() ? 'opacity-50' : ''}>Code Style Review (after review)</span>
              </label>
              <label class="checkbox-item">
                <input 
                  type="checkbox" 
                  checked={autoCommit()} 
                  onChange={(e) => setAutoCommit(e.currentTarget.checked)} 
                />
                <span>Auto-commit</span>
              </label>
              <label class="checkbox-item">
                <input 
                  type="checkbox" 
                  checked={deleteWorktree()} 
                  onChange={(e) => setDeleteWorktree(e.currentTarget.checked)} 
                />
                <span>Delete Worktree</span>
              </label>
              <label class="checkbox-item">
                <input 
                  type="checkbox" 
                  checked={skipPermissionAsking()} 
                  onChange={(e) => setSkipPermissionAsking(e.currentTarget.checked)} 
                />
                <span>Skip Permission Asking</span>
              </label>
            </div>
          </Show>

          {/* Requirements */}
          <div class="form-group">
            <div class="label-row">
              <label>Requirements (dependencies)</label>
              <HelpButton tooltip="Tasks that must be completed before this one should run." />
            </div>
            <div class="border border-dark-surface3 rounded-lg p-1.5 max-h-36 overflow-y-auto">
              <For each={availableRequirements()}>
                {(t) => (
                  <label
                    class="checkbox-item p-1 rounded hover:bg-dark-surface2"
                  >
                    <input
                      type="checkbox"
                      checked={requirements().includes(t.id)}
                      onChange={() => toggleRequirement(t.id)}
                      disabled={isViewOnly()}
                    />
                    <span class="text-sm">{t.name} (#{t.idx + 1})</span>
                  </label>
                )}
              </For>
              <Show when={availableRequirements().length === 0}>
                <div class="text-xs text-dark-text-muted p-1">No other tasks</div>
              </Show>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn" onClick={props.onClose}>Cancel</button>
            <Show when={!isViewOnly()}>
              <button type="submit" class="btn btn-primary">
                {getSaveButtonText()}
              </button>
            </Show>
          </div>
        </form>
      </Show>
    </ModalWrapper>
  )
}
