// src/kanban-react/src/components/modals/BatchEditModal.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { ModalWrapper } from '../common/ModalWrapper'
import { useTasksContext, useToastContext, useModelSearchContext } from '@/contexts/AppContext'
import { useApi } from '@/hooks/useApi'
import type { ThinkingLevel, TaskStatus, Task } from '@/types'

interface BatchEditModalProps {
  taskIds: string[]
  onClose: () => void
}

type FieldValue<T> =
  | { kind: 'unchanged' }
  | { kind: 'mixed' }
  | { kind: 'set'; value: T }
  | { kind: 'cleared' }

interface FormState {
  status: FieldValue<TaskStatus>
  branch: FieldValue<string>
  planModel: FieldValue<string>
  executionModel: FieldValue<string>
  thinkingLevel: FieldValue<ThinkingLevel>
  maxReviewRunsOverride: FieldValue<number | null>
  planmode: FieldValue<boolean>
  autoApprovePlan: FieldValue<boolean>
  review: FieldValue<boolean>
  codeStyleReview: FieldValue<boolean>
  autoCommit: FieldValue<boolean>
  deleteWorktree: FieldValue<boolean>
  skipPermissionAsking: FieldValue<boolean>
}

const UNCHANGED = <T,>(): FieldValue<T> => ({ kind: 'unchanged' })
const MIXED = <T,>(): FieldValue<T> => ({ kind: 'mixed' })
const SET = <T,>(value: T): FieldValue<T> => ({ kind: 'set', value })
const CLEARED = <T,>(): FieldValue<T> => ({ kind: 'cleared' })

const isModified = <T,>(fv: FieldValue<T>): boolean => fv.kind !== 'unchanged'

const getInputValue = <T,>(fv: FieldValue<T>): T | '' | 'mixed' => {
  if (fv.kind === 'set') return fv.value
  if (fv.kind === 'mixed') return 'mixed' as unknown as T
  return '' as T
}

const getCheckboxState = (fv: FieldValue<boolean>): { checked: boolean; indeterminate: boolean } => {
  if (fv.kind === 'set') return { checked: fv.value, indeterminate: false }
  if (fv.kind === 'mixed') return { checked: false, indeterminate: true }
  return { checked: false, indeterminate: false }
}

const getMixedDisplay = (fv: FieldValue<unknown>): string => {
  return fv.kind === 'mixed' ? ' (mixed)' : ''
}

export function BatchEditModal({ taskIds, onClose }: BatchEditModalProps) {
  const tasks = useTasksContext()
  const toasts = useToastContext()
  const modelSearch = useModelSearchContext()
  const api = useApi()

  const [branches, setBranches] = useState<string[]>([])
  const [branchesLoading, setBranchesLoading] = useState(false)
  const [branchesError, setBranchesError] = useState<string | null>(null)

  const planmodeRef = useRef<HTMLInputElement>(null)
  const autoApprovePlanRef = useRef<HTMLInputElement>(null)
  const reviewRef = useRef<HTMLInputElement>(null)
  const codeStyleReviewRef = useRef<HTMLInputElement>(null)
  const autoCommitRef = useRef<HTMLInputElement>(null)
  const deleteWorktreeRef = useRef<HTMLInputElement>(null)
  const skipPermissionAskingRef = useRef<HTMLInputElement>(null)

  const checkboxRefs = {
    planmode: planmodeRef,
    autoApprovePlan: autoApprovePlanRef,
    review: reviewRef,
    codeStyleReview: codeStyleReviewRef,
    autoCommit: autoCommitRef,
    deleteWorktree: deleteWorktreeRef,
    skipPermissionAsking: skipPermissionAskingRef,
  }

  const [form, setForm] = useState<FormState>({
    status: UNCHANGED(),
    branch: UNCHANGED(),
    planModel: UNCHANGED(),
    executionModel: UNCHANGED(),
    thinkingLevel: UNCHANGED(),
    maxReviewRunsOverride: UNCHANGED(),
    planmode: UNCHANGED(),
    autoApprovePlan: UNCHANGED(),
    review: UNCHANGED(),
    codeStyleReview: UNCHANGED(),
    autoCommit: UNCHANGED(),
    deleteWorktree: UNCHANGED(),
    skipPermissionAsking: UNCHANGED(),
  })

  const [isLoading, setIsLoading] = useState(false)

  const getCommonValue = useCallback(<K extends keyof Task>(tasks: Task[], key: K): Task[K] | undefined => {
    if (tasks.length === 0) return undefined
    const first = tasks[0][key]
    for (let i = 1; i < tasks.length; i++) {
      if (tasks[i][key] !== first) return undefined
    }
    return first
  }, [])

  const allSame = useCallback(<K extends keyof Task>(tasks: Task[], key: K): boolean => {
    if (tasks.length <= 1) return true
    const first = tasks[0][key]
    return tasks.every(t => t[key] === first)
  }, [])

  useEffect(() => {
    const selectedTasks = tasks.tasks.filter(t => taskIds.includes(t.id))
    if (selectedTasks.length === 0) return

    const newForm: FormState = {
      status: UNCHANGED(),
      branch: UNCHANGED(),
      planModel: UNCHANGED(),
      executionModel: UNCHANGED(),
      thinkingLevel: UNCHANGED(),
      maxReviewRunsOverride: UNCHANGED(),
      planmode: UNCHANGED(),
      autoApprovePlan: UNCHANGED(),
      review: UNCHANGED(),
      codeStyleReview: UNCHANGED(),
      autoCommit: UNCHANGED(),
      deleteWorktree: UNCHANGED(),
      skipPermissionAsking: UNCHANGED(),
    }

    const statusVal = getCommonValue(selectedTasks, 'status')
    newForm.status = statusVal !== undefined ? SET(statusVal) : MIXED()

    const branchVal = getCommonValue(selectedTasks, 'branch')
    newForm.branch = branchVal !== undefined ? SET(branchVal) : MIXED()

    const planModelVal = getCommonValue(selectedTasks, 'planModel')
    newForm.planModel = planModelVal !== undefined ? SET(planModelVal) : MIXED()

    const execModelVal = getCommonValue(selectedTasks, 'executionModel')
    newForm.executionModel = execModelVal !== undefined ? SET(execModelVal) : MIXED()

    const thinkVal = getCommonValue(selectedTasks, 'thinkingLevel')
    newForm.thinkingLevel = thinkVal !== undefined ? SET(thinkVal) : MIXED()

    if (allSame(selectedTasks, 'maxReviewRunsOverride')) {
      const maxRevVal = selectedTasks[0].maxReviewRunsOverride
      newForm.maxReviewRunsOverride = maxRevVal !== undefined ? SET(maxRevVal) : SET(null)
    } else {
      newForm.maxReviewRunsOverride = MIXED()
    }

    if (allSame(selectedTasks, 'planmode')) {
      newForm.planmode = SET(selectedTasks[0].planmode)
    } else {
      newForm.planmode = MIXED()
    }

    if (allSame(selectedTasks, 'autoApprovePlan')) {
      newForm.autoApprovePlan = SET(selectedTasks[0].autoApprovePlan)
    } else {
      newForm.autoApprovePlan = MIXED()
    }

    if (allSame(selectedTasks, 'review')) {
      newForm.review = SET(selectedTasks[0].review)
    } else {
      newForm.review = MIXED()
    }

    if (allSame(selectedTasks, 'codeStyleReview')) {
      newForm.codeStyleReview = SET(selectedTasks[0].codeStyleReview)
    } else {
      newForm.codeStyleReview = MIXED()
    }

    if (allSame(selectedTasks, 'autoCommit')) {
      newForm.autoCommit = SET(selectedTasks[0].autoCommit)
    } else {
      newForm.autoCommit = MIXED()
    }

    if (allSame(selectedTasks, 'deleteWorktree')) {
      newForm.deleteWorktree = SET(selectedTasks[0].deleteWorktree)
    } else {
      newForm.deleteWorktree = MIXED()
    }

    if (allSame(selectedTasks, 'skipPermissionAsking')) {
      newForm.skipPermissionAsking = SET(selectedTasks[0].skipPermissionAsking)
    } else {
      newForm.skipPermissionAsking = MIXED()
    }

    setForm(newForm)
  }, [taskIds, tasks.tasks, getCommonValue, allSame])

  useEffect(() => {
    setBranchesLoading(true)
    setBranchesError(null)
    api.getBranches()
      .then((data) => {
        setBranches(data.branches || [])
      })
      .catch((err) => {
        setBranchesError(err instanceof Error ? err.message : 'Failed to load branches')
      })
      .finally(() => {
        setBranchesLoading(false)
      })
  }, [api])

  useEffect(() => {
    (Object.keys(checkboxRefs) as Array<keyof typeof checkboxRefs>).forEach(key => {
      const ref = checkboxRefs[key]
      if (ref.current) {
        const state = getCheckboxState(form[key] as FieldValue<boolean>)
        ref.current.indeterminate = state.indeterminate
      }
    })
  }, [form])

  const handleSelectChange = <K extends keyof FormState>(
    key: K,
    value: FormState[K] extends FieldValue<infer T> ? T : never
  ) => {
    setForm(prev => ({ ...prev, [key]: SET(value) }))
  }

  const handleClear = (key: keyof FormState) => {
    setForm(prev => ({ ...prev, [key]: CLEARED() }))
  }

  const handleCheckboxChange = (key: keyof FormState) => {
    setForm(prev => {
      const current = prev[key] as FieldValue<boolean>
      if (current.kind === 'set') {
        return { ...prev, [key]: SET(!current.value) }
      }
      return { ...prev, [key]: SET(true) }
    })
  }

  const handleMaxReviewChange = (value: string) => {
    if (value === '') {
      setForm(prev => ({ ...prev, maxReviewRunsOverride: CLEARED() }))
    } else {
      const num = parseInt(value, 10)
      if (!isNaN(num) && num >= 0) {
        setForm(prev => ({ ...prev, maxReviewRunsOverride: SET(num) }))
      }
    }
  }

  const buildUpdatePayload = () => {
    const payload: Partial<Task> = {}

    if (form.status.kind === 'set') payload.status = form.status.value
    if (form.branch.kind === 'set') payload.branch = form.branch.value
    if (form.branch.kind === 'cleared') payload.branch = ''
    if (form.planModel.kind === 'set') payload.planModel = form.planModel.value
    if (form.executionModel.kind === 'set') payload.executionModel = form.executionModel.value
    if (form.thinkingLevel.kind === 'set') payload.thinkingLevel = form.thinkingLevel.value

    if (form.maxReviewRunsOverride.kind === 'set') {
      payload.maxReviewRunsOverride = form.maxReviewRunsOverride.value ?? undefined
    } else if (form.maxReviewRunsOverride.kind === 'cleared') {
      payload.maxReviewRunsOverride = undefined
    }

    if (form.planmode.kind === 'set') payload.planmode = form.planmode.value
    if (form.autoApprovePlan.kind === 'set') payload.autoApprovePlan = form.autoApprovePlan.value
    if (form.review.kind === 'set') payload.review = form.review.value
    if (form.codeStyleReview.kind === 'set') payload.codeStyleReview = form.codeStyleReview.value
    if (form.autoCommit.kind === 'set') payload.autoCommit = form.autoCommit.value
    if (form.deleteWorktree.kind === 'set') payload.deleteWorktree = form.deleteWorktree.value
    if (form.skipPermissionAsking.kind === 'set') payload.skipPermissionAsking = form.skipPermissionAsking.value

    return payload
  }

  const modifiedCount = Object.values(form).filter(isModified).length

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (modifiedCount === 0) {
      toasts.showToast('No changes to apply', 'info')
      return
    }

    setIsLoading(true)

    const updates = buildUpdatePayload()

    try {
      await Promise.all(taskIds.map(id => tasks.updateTask(id, updates)))
      toasts.showToast(`Updated ${taskIds.length} tasks`, 'success')
      onClose()
    } catch (e) {
      toasts.showToast(e instanceof Error ? e.message : 'Failed to update tasks', 'error')
    } finally {
      setIsLoading(false)
    }
  }

  const inputValue = getInputValue(form.status)
  const branchValue = getInputValue(form.branch)
  const planModelValue = getInputValue(form.planModel)
  const execModelValue = getInputValue(form.executionModel)
  const thinkingValue = getInputValue(form.thinkingLevel)
  const maxReviewValue = form.maxReviewRunsOverride.kind === 'set'
    ? (form.maxReviewRunsOverride.value ?? '')
    : form.maxReviewRunsOverride.kind === 'mixed'
      ? 'mixed'
      : ''

  const checkboxFields: { key: keyof FormState; label: string }[] = [
    { key: 'planmode', label: 'Plan Mode' },
    { key: 'autoApprovePlan', label: 'Auto-approve Plan' },
    { key: 'review', label: 'Review' },
    { key: 'codeStyleReview', label: 'Code Style Review' },
    { key: 'autoCommit', label: 'Auto-commit' },
    { key: 'deleteWorktree', label: 'Delete Worktree' },
    { key: 'skipPermissionAsking', label: 'Skip Permission Asking' },
  ]

  return (
    <ModalWrapper title={`Batch Edit: ${taskIds.length} Tasks`} onClose={onClose}>
      <form onSubmit={handleSubmit} className="space-y-4">
        <p className="text-sm text-dark-text-muted">
          Select the fields you want to update. Fields showing "mixed" have different values across selected tasks.
        </p>

        <div className="form-group">
          <label className="flex items-center gap-2">
            Status
            {getMixedDisplay(form.status) && (
              <span className="text-xs text-amber-400">{getMixedDisplay(form.status)}</span>
            )}
          </label>
          <select
            className="form-select"
            value={inputValue}
            onChange={(e) => handleSelectChange('status', e.target.value as TaskStatus)}
          >
            <option value="">Keep current</option>
            <option value="template">Template</option>
            <option value="backlog">Backlog</option>
            <option value="executing">Executing</option>
            <option value="review">Review</option>
            <option value="done">Done</option>
          </select>
        </div>

        <div className="form-group">
          <label className="flex items-center gap-2">
            Branch
            {getMixedDisplay(form.branch) && (
              <span className="text-xs text-amber-400">{getMixedDisplay(form.branch)}</span>
            )}
          </label>
          {branchesLoading ? (
            <div className="text-sm text-dark-text-muted">Loading branches...</div>
          ) : branchesError ? (
            <div className="text-sm text-red-400">{branchesError}</div>
          ) : (
            <select
              className="form-select"
              value={branchValue}
              onChange={(e) => handleSelectChange('branch', e.target.value)}
            >
              <option value="">Keep current</option>
              {branches.map(b => (
                <option key={b} value={b}>{b}</option>
              ))}
            </select>
          )}
        </div>

        <div className="form-group">
          <label className="flex items-center gap-2">
            Plan Model
            {getMixedDisplay(form.planModel) && (
              <span className="text-xs text-amber-400">{getMixedDisplay(form.planModel)}</span>
            )}
          </label>
          <select
            className="form-select"
            value={planModelValue}
            onChange={(e) => handleSelectChange('planModel', e.target.value)}
          >
            <option value="">Keep current</option>
            {modelSearch.getModelOptions().map(opt => (
              <option key={opt.value} value={opt.value}>{opt.label}</option>
            ))}
          </select>
        </div>

        <div className="form-group">
          <label className="flex items-center gap-2">
            Execution Model
            {getMixedDisplay(form.executionModel) && (
              <span className="text-xs text-amber-400">{getMixedDisplay(form.executionModel)}</span>
            )}
          </label>
          <select
            className="form-select"
            value={execModelValue}
            onChange={(e) => handleSelectChange('executionModel', e.target.value)}
          >
            <option value="">Keep current</option>
            {modelSearch.getModelOptions().map(opt => (
              <option key={opt.value} value={opt.value}>{opt.label}</option>
            ))}
          </select>
        </div>

        <div className="form-group">
          <label className="flex items-center gap-2">
            Thinking Level
            {getMixedDisplay(form.thinkingLevel) && (
              <span className="text-xs text-amber-400">{getMixedDisplay(form.thinkingLevel)}</span>
            )}
          </label>
          <select
            className="form-select"
            value={thinkingValue}
            onChange={(e) => handleSelectChange('thinkingLevel', e.target.value as ThinkingLevel)}
          >
            <option value="">Keep current</option>
            <option value="default">Default</option>
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
          </select>
        </div>

        <div className="form-group">
          <label className="flex items-center gap-2">
            Max Reviews Override
            {getMixedDisplay(form.maxReviewRunsOverride) && (
              <span className="text-xs text-amber-400">{getMixedDisplay(form.maxReviewRunsOverride)}</span>
            )}
          </label>
          <div className="flex items-center gap-2">
            <input
              type="number"
              className="form-input w-32"
              min="0"
              placeholder={form.maxReviewRunsOverride.kind === 'mixed' ? 'mixed' : 'Keep current'}
              value={maxReviewValue === 'mixed' ? '' : maxReviewValue}
              onChange={(e) => handleMaxReviewChange(e.target.value)}
            />
            <button
              type="button"
              className="btn btn-sm"
              onClick={() => handleClear('maxReviewRunsOverride')}
              title="Clear override (use default)"
            >
              Clear
            </button>
          </div>
          <p className="text-xs text-dark-text-muted mt-1">
            Leave empty to keep current, 0 to clear override, or set a value.
          </p>
        </div>

        <div className="border-t border-dark-border pt-4 mt-4">
          <p className="text-sm font-medium text-dark-text-secondary mb-3">Options</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {checkboxFields.map(({ key, label }) => {
              const state = getCheckboxState(form[key] as FieldValue<boolean>)
              const isMixed = (form[key] as FieldValue<boolean>).kind === 'mixed'
              return (
                <label key={key} className="flex items-center gap-2 cursor-pointer hover:bg-dark-surface p-2 rounded">
                  <input
                    ref={checkboxRefs[key as keyof typeof checkboxRefs]}
                    type="checkbox"
                    className="form-checkbox"
                    checked={state.checked}
                    onChange={() => handleCheckboxChange(key)}
                  />
                  <span className="text-sm">
                    {label}
                    {isMixed && (
                      <span className="text-xs text-amber-400 ml-1">(mixed)</span>
                    )}
                  </span>
                </label>
              )
            })}
          </div>
        </div>

        <div className="modal-footer">
          <div className="flex items-center gap-2">
            <span className="text-sm text-dark-text-muted">
              {modifiedCount} field{modifiedCount !== 1 ? 's' : ''} modified
            </span>
          </div>
          <div className="flex items-center gap-2">
            <button type="button" className="btn" onClick={onClose} disabled={isLoading}>Cancel</button>
            <button
              type="submit"
              className="btn btn-primary"
              disabled={isLoading || modifiedCount === 0}
            >
              {isLoading ? 'Updating...' : `Update ${taskIds.length} Tasks`}
            </button>
          </div>
        </div>
      </form>
    </ModalWrapper>
  )
}

// src/kanban-vue/src/components/modals/BatchEditModal.vue
<script setup lang="ts">
import { ref, computed, inject, onMounted } from 'vue'
import type { Task, UpdateTaskDTO, BestOfNSlot, ThinkingLevel, ExecutionStrategy } from '@/types/api'
import type { useTasks } from '@/composables/useTasks'
import type { useModelSearch } from '@/composables/useModelSearch'
import type { useToasts } from '@/composables/useToasts'
import ModelPicker from '../common/ModelPicker.vue'

const props = defineProps<{
  taskIds: string[]
}>()

const emit = defineEmits<{
  close: []
}>()

const tasks = inject<ReturnType<typeof useTasks>>('tasks')!
const modelSearch = inject<ReturnType<typeof useModelSearch>>('modelSearch')!
const toasts = inject<ReturnType<typeof useToasts>>('toasts')!

const isLoading = ref(false)

// Get all selected tasks
const selectedTasks = computed(() => {
  return props.taskIds
    .map(id => tasks.getTaskById(id))
    .filter((t): t is Task => t !== undefined)
})

// Check if all values are the same
const isUniform = <T,>(values: T[]): boolean => {
  if (values.length === 0) return true
  const first = JSON.stringify(values[0])
  return values.every(v => JSON.stringify(v) === first)
}

// Get common value or undefined (for mixed)
const getCommonValue = <T,>(values: T[]): T | undefined => {
  if (values.length === 0 || !isUniform(values)) return undefined
  return values[0]
}

// Form state with "mixed" handling
const form = ref({
  branch: '' as string | undefined,
  branchMixed: false,
  planModel: '' as string | undefined,
  planModelMixed: false,
  executionModel: '' as string | undefined,
  executionModelMixed: false,
  planmode: undefined as boolean | undefined,
  planmodeMixed: false,
  autoApprovePlan: undefined as boolean | undefined,
  autoApprovePlanMixed: false,
  review: undefined as boolean | undefined,
  reviewMixed: false,
  autoCommit: undefined as boolean | undefined,
  autoCommitMixed: false,
  deleteWorktree: undefined as boolean | undefined,
  deleteWorktreeMixed: false,
  skipPermissionAsking: undefined as boolean | undefined,
  skipPermissionAskingMixed: false,
  thinkingLevel: '' as ThinkingLevel | undefined,
  thinkingLevelMixed: false,
  executionStrategy: '' as ExecutionStrategy | undefined,
  executionStrategyMixed: false,
  maxReviewRunsOverride: undefined as number | undefined,
  maxReviewRunsOverrideMixed: false,
  // Best-of-N config (only editable if all tasks have best_of_n strategy)
  bonWorkers: [] as BestOfNSlot[],
  bonReviewers: [] as BestOfNSlot[],
  bonFinalApplierModel: '' as string | undefined,
  bonFinalApplierSuffix: '',
  bonSelectionMode: 'pick_best' as const,
  bonMinSuccessful: 1,
  bonVerificationCmd: '',
  bonConfigEnabled: false,
  bonConfigMixed: false,
})

const bonValidationErrors = ref<string[]>([])
const availableBranches = ref<string[]>([])

// Track which fields have been explicitly modified by the user
const modifiedFields = ref<Set<string>>(new Set())

const markModified = (field: string) => {
  modifiedFields.value.add(field)
}

onMounted(async () => {
  // Load branches
  try {
    const branchData = await tasks.api.getBranches()
    availableBranches.value = branchData.branches
  } catch {
    // Use empty branches
  }

  // Initialize form with common values from selected tasks
  const taskList = selectedTasks.value
  if (taskList.length === 0) return

  // Branch
  const branches = taskList.map(t => t.branch)
  form.value.branch = getCommonValue(branches)
  form.value.branchMixed = !isUniform(branches)

  // Models
  const planModels = taskList.map(t => t.planModel || 'default')
  form.value.planModel = getCommonValue(planModels)
  form.value.planModelMixed = !isUniform(planModels)

  const execModels = taskList.map(t => t.executionModel || 'default')
  form.value.executionModel = getCommonValue(execModels)
  form.value.executionModelMixed = !isUniform(execModels)

  // Checkboxes
  const planmodes = taskList.map(t => t.planmode)
  form.value.planmode = getCommonValue(planmodes)
  form.value.planmodeMixed = !isUniform(planmodes)

  const autoApprovePlans = taskList.map(t => t.autoApprovePlan)
  form.value.autoApprovePlan = getCommonValue(autoApprovePlans)
  form.value.autoApprovePlanMixed = !isUniform(autoApprovePlans)

  const reviews = taskList.map(t => t.review)
  form.value.review = getCommonValue(reviews)
  form.value.reviewMixed = !isUniform(reviews)

  const autoCommits = taskList.map(t => t.autoCommit)
  form.value.autoCommit = getCommonValue(autoCommits)
  form.value.autoCommitMixed = !isUniform(autoCommits)

  const deleteWorktrees = taskList.map(t => t.deleteWorktree)
  form.value.deleteWorktree = getCommonValue(deleteWorktrees)
  form.value.deleteWorktreeMixed = !isUniform(deleteWorktrees)

  const skipPerms = taskList.map(t => t.skipPermissionAsking)
  form.value.skipPermissionAsking = getCommonValue(skipPerms)
  form.value.skipPermissionAskingMixed = !isUniform(skipPerms)

  // Dropdowns
  const thinkingLevels = taskList.map(t => t.thinkingLevel)
  form.value.thinkingLevel = getCommonValue(thinkingLevels)
  form.value.thinkingLevelMixed = !isUniform(thinkingLevels)

  const execStrategies = taskList.map(t => t.executionStrategy)
  form.value.executionStrategy = getCommonValue(execStrategies)
  form.value.executionStrategyMixed = !isUniform(execStrategies)

  // Max reviews
  const maxReviews = taskList.map(t => t.maxReviewRunsOverride)
  form.value.maxReviewRunsOverride = getCommonValue(maxReviews)
  form.value.maxReviewRunsOverrideMixed = !isUniform(maxReviews)

  // Best-of-N config - only enable if all tasks are best_of_n
  const allBestOfN = taskList.every(t => t.executionStrategy === 'best_of_n')
  form.value.bonConfigEnabled = allBestOfN

  if (allBestOfN) {
    // Check if all configs are the same
    const configs = taskList.map(t => JSON.stringify(t.bestOfNConfig))
    form.value.bonConfigMixed = !isUniform(configs)

    // Use first task's config as default (or mixed indicator)
    const firstConfig = taskList[0].bestOfNConfig
    if (firstConfig && !form.value.bonConfigMixed) {
      form.value.bonWorkers = firstConfig.workers.map(w => ({ ...w }))
      form.value.bonReviewers = firstConfig.reviewers.map(r => ({ ...r }))
      form.value.bonFinalApplierModel = firstConfig.finalApplier.model
      form.value.bonFinalApplierSuffix = firstConfig.finalApplier.taskSuffix || ''
      form.value.bonSelectionMode = firstConfig.selectionMode
      form.value.bonMinSuccessful = firstConfig.minSuccessfulWorkers
      form.value.bonVerificationCmd = firstConfig.verificationCommand || ''
    }
  }
})

const showBonConfig = computed(() => 
  form.value.executionStrategy === 'best_of_n' || 
  (form.value.executionStrategyMixed && form.value.bonConfigEnabled)
)

const validateBonConfig = (): string[] => {
  const errors: string[] = []
  if (form.value.bonWorkers.length === 0) {
    errors.push('Add at least one worker slot')
  }
  const totalWorkers = form.value.bonWorkers.reduce((sum, w) => sum + (w.count || 1), 0)
  if (totalWorkers > 8) {
    errors.push(`Total workers (${totalWorkers}) exceeds maximum of 8`)
  }
  if (form.value.bonMinSuccessful > totalWorkers) {
    errors.push('Minimum successful workers cannot exceed total workers')
  }
  return errors
}

const addBonWorker = () => {
  form.value.bonWorkers.push({ model: 'default', count: 1, suffix: '' })
  markModified('bestOfNConfig')
}

const removeBonWorker = (index: number) => {
  form.value.bonWorkers.splice(index, 1)
  markModified('bestOfNConfig')
}

const addBonReviewer = () => {
  form.value.bonReviewers.push({ model: 'default', count: 1, suffix: '' })
  markModified('bestOfNConfig')
}

const removeBonReviewer = (index: number) => {
  form.value.bonReviewers.splice(index, 1)
  markModified('bestOfNConfig')
}

const save = async () => {
  if (selectedTasks.value.length === 0) {
    emit('close')
    return
  }

  // Validate best-of-n if enabled and modified
  if (showBonConfig.value && modifiedFields.value.has('bestOfNConfig')) {
    const errors = validateBonConfig()
    if (errors.length > 0) {
      bonValidationErrors.value = errors
      toasts.showToast('Invalid best-of-n configuration: ' + errors.join('; '), 'error')
      return
    }
  }

  isLoading.value = true
  try {
    const updateData: UpdateTaskDTO = {}

    // Only include fields that were explicitly modified
    if (modifiedFields.value.has('branch') && form.value.branch !== undefined) {
      updateData.branch = form.value.branch
    }
    if (modifiedFields.value.has('planModel') && form.value.planModel !== undefined) {
      updateData.planModel = modelSearch.normalizeValue(form.value.planModel)
    }
    if (modifiedFields.value.has('executionModel') && form.value.executionModel !== undefined) {
      updateData.executionModel = modelSearch.normalizeValue(form.value.executionModel)
    }
    if (modifiedFields.value.has('planmode') && form.value.planmode !== undefined) {
      updateData.planmode = form.value.planmode
    }
    if (modifiedFields.value.has('autoApprovePlan') && form.value.autoApprovePlan !== undefined) {
      updateData.autoApprovePlan = form.value.autoApprovePlan
    }
    if (modifiedFields.value.has('review') && form.value.review !== undefined) {
      updateData.review = form.value.review
    }
    if (modifiedFields.value.has('autoCommit') && form.value.autoCommit !== undefined) {
      updateData.autoCommit = form.value.autoCommit
    }
    if (modifiedFields.value.has('deleteWorktree') && form.value.deleteWorktree !== undefined) {
      updateData.deleteWorktree = form.value.deleteWorktree
    }
    if (modifiedFields.value.has('skipPermissionAsking') && form.value.skipPermissionAsking !== undefined) {
      updateData.skipPermissionAsking = form.value.skipPermissionAsking
    }
    if (modifiedFields.value.has('thinkingLevel') && form.value.thinkingLevel !== undefined) {
      updateData.thinkingLevel = form.value.thinkingLevel
    }
    if (modifiedFields.value.has('executionStrategy') && form.value.executionStrategy !== undefined) {
      updateData.executionStrategy = form.value.executionStrategy
    }
    if (modifiedFields.value.has('maxReviewRunsOverride')) {
      updateData.maxReviewRunsOverride = form.value.maxReviewRunsOverride
    }

    // Best-of-N config
    if (modifiedFields.value.has('bestOfNConfig') && showBonConfig.value) {
      updateData.bestOfNConfig = {
        workers: form.value.bonWorkers.map(w => ({
          model: w.model,
          count: w.count || 1,
          taskSuffix: w.suffix || undefined,
        })),
        reviewers: form.value.bonReviewers.map(r => ({
          model: r.model,
          count: r.count || 1,
          taskSuffix: r.suffix || undefined,
        })),
        finalApplier: {
          model: modelSearch.normalizeValue(form.value.bonFinalApplierModel || 'default'),
          taskSuffix: form.value.bonFinalApplierSuffix.trim() || undefined,
        },
        selectionMode: form.value.bonSelectionMode,
        minSuccessfulWorkers: form.value.bonMinSuccessful,
        verificationCommand: form.value.bonVerificationCmd.trim() || undefined,
      }
    }

    // Update all tasks in parallel
    const results = await Promise.all(
      props.taskIds.map(id => tasks.updateTask(id, updateData))
    )

    toasts.showToast(`Updated ${results.length} tasks`, 'success')
    emit('close')
  } catch (e) {
    toasts.showToast('Update failed: ' + (e instanceof Error ? e.message : String(e)), 'error')
  } finally {
    isLoading.value = false
  }
}

const closeOnOverlay = (e: MouseEvent) => {
  if (e.target === e.currentTarget) {
    emit('close')
  }
}

// Helper to render mixed state indicator
const mixedIndicator = (isMixed: boolean) => isMixed ? '— ' : ''
</script>

<template>
  <div class="modal-overlay" @mousedown="closeOnOverlay">
    <div class="modal w-[min(640px,calc(100vw-40px))] max-h-[min(880px,calc(100vh-40px))]">
      <div class="modal-header">
        <h2>Edit {{ selectedCount }} Tasks</h2>
        <button class="modal-close" @click="emit('close')">×</button>
      </div>

      <div class="modal-body space-y-3">
        <div class="text-sm text-dark-text-muted mb-4">
          Only modified fields will be updated. Fields showing "—" have mixed values across selected tasks.
        </div>

        <!-- Branch -->
        <div class="form-group">
          <div class="label-row">
            <label>Branch</label>
            <span v-if="form.branchMixed" class="text-xs text-amber-400">(mixed)</span>
          </div>
          <select 
            v-model="form.branch" 
            class="form-select"
            @change="markModified('branch')"
          >
            <option value="" disabled v-if="form.branchMixed">— (mixed values)</option>
            <option v-for="branch in availableBranches" :key="branch" :value="branch">
              {{ mixedIndicator(form.branchMixed) }}{{ branch }}
            </option>
          </select>
        </div>

        <!-- Models -->
        <div class="grid grid-cols-2 gap-3">
          <div class="form-group">
            <div class="label-row">
              <label>Plan Model</label>
              <span v-if="form.planModelMixed" class="text-xs text-amber-400">(mixed)</span>
            </div>
            <select
              v-model="form.planModel"
              class="form-select"
              @change="markModified('planModel')"
            >
              <option value="" disabled v-if="form.planModelMixed">— (mixed values)</option>
              <option
                v-for="opt in modelSearch.getModelOptions(form.planModel || 'default')"
                :key="opt.value"
                :value="opt.value"
              >
                {{ mixedIndicator(form.planModelMixed) }}{{ opt.label }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <div class="label-row">
              <label>Execution Model</label>
              <span v-if="form.executionModelMixed" class="text-xs text-amber-400">(mixed)</span>
            </div>
            <select
              v-model="form.executionModel"
              class="form-select"
              @change="markModified('executionModel')"
            >
              <option value="" disabled v-if="form.executionModelMixed">— (mixed values)</option>
              <option
                v-for="opt in modelSearch.getModelOptions(form.executionModel || 'default')"
                :key="opt.value"
                :value="opt.value"
              >
                {{ mixedIndicator(form.executionModelMixed) }}{{ opt.label }}
              </option>
            </select>
          </div>
        </div>

        <!-- Thinking Level -->
        <div class="form-group">
          <div class="label-row">
            <label>Thinking Level</label>
            <span v-if="form.thinkingLevelMixed" class="text-xs text-amber-400">(mixed)</span>
          </div>
          <select 
            v-model="form.thinkingLevel" 
            class="form-select"
            @change="markModified('thinkingLevel')"
          >
            <option value="" disabled v-if="form.thinkingLevelMixed">— (mixed values)</option>
            <option value="default">{{ mixedIndicator(form.thinkingLevelMixed) }}Default</option>
            <option value="low">{{ mixedIndicator(form.thinkingLevelMixed) }}Low</option>
            <option value="medium">{{ mixedIndicator(form.thinkingLevelMixed) }}Medium</option>
            <option value="high">{{ mixedIndicator(form.thinkingLevelMixed) }}High</option>
          </select>
        </div>

        <!-- Execution Strategy -->
        <div class="form-group">
          <div class="label-row">
            <label>Execution Strategy</label>
            <span v-if="form.executionStrategyMixed" class="text-xs text-amber-400">(mixed)</span>
          </div>
          <select 
            v-model="form.executionStrategy" 
            class="form-select"
            @change="markModified('executionStrategy')"
          >
            <option value="" disabled v-if="form.executionStrategyMixed">— (mixed values)</option>
            <option value="standard">{{ mixedIndicator(form.executionStrategyMixed) }}Standard</option>
            <option value="best_of_n">{{ mixedIndicator(form.executionStrategyMixed) }}Best of N</option>
          </select>
        </div>

        <!-- Best-of-N Config -->
        <div v-if="showBonConfig" class="border border-dark-surface3 rounded-lg p-3 bg-dark-bg">
          <div class="flex items-center justify-between mb-2">
            <h4 class="text-sm font-semibold">Best of N Configuration</h4>
            <span v-if="form.bonConfigMixed" class="text-xs text-amber-400">(mixed values)</span>
          </div>

          <div v-if="bonValidationErrors.length > 0" class="mb-2 space-y-1">
            <div v-for="err in bonValidationErrors" :key="err" class="text-xs text-red-400">
              {{ err }}
            </div>
          </div>

          <!-- Workers -->
          <div class="form-group">
            <label>Workers</label>
            <div class="space-y-2">
              <div
                v-for="(slot, i) in form.bonWorkers"
                :key="i"
                class="flex gap-2 items-center"
              >
                <input
                  v-model.number="slot.count"
                  type="number"
                  min="1"
                  max="4"
                  class="form-input w-16"
                  @change="markModified('bestOfNConfig')"
                />
                <select v-model="slot.model" class="form-select flex-1" @change="markModified('bestOfNConfig')">
                  <option
                    v-for="opt in modelSearch.getModelOptions(slot.model)"
                    :key="opt.value"
                    :value="opt.value"
                  >
                    {{ opt.label }}
                  </option>
                </select>
                <input
                  v-model="slot.suffix"
                  type="text"
                  placeholder="Suffix (optional)"
                  class="form-input flex-1"
                  @change="markModified('bestOfNConfig')"
                />
                <button
                  class="text-red-400 hover:text-red-300 px-2"
                  @click="removeBonWorker(i)"
                >
                  ✕
                </button>
              </div>
            </div>
            <button class="add-task-btn mt-2" @click="addBonWorker">
              + Add Worker Slot
            </button>
          </div>

          <!-- Reviewers -->
          <div class="form-group">
            <label>Reviewers</label>
            <div class="space-y-2">
              <div
                v-for="(slot, i) in form.bonReviewers"
                :key="i"
                class="flex gap-2 items-center"
              >
                <input
                  v-model.number="slot.count"
                  type="number"
                  min="1"
                  max="4"
                  class="form-input w-16"
                  @change="markModified('bestOfNConfig')"
                />
                <select v-model="slot.model" class="form-select flex-1" @change="markModified('bestOfNConfig')">
                  <option
                    v-for="opt in modelSearch.getModelOptions(slot.model)"
                    :key="opt.value"
                    :value="opt.value"
                  >
                    {{ opt.label }}
                  </option>
                </select>
                <input
                  v-model="slot.suffix"
                  type="text"
                  placeholder="Suffix (optional)"
                  class="form-input flex-1"
                  @change="markModified('bestOfNConfig')"
                />
                <button
                  class="text-red-400 hover:text-red-300 px-2"
                  @click="removeBonReviewer(i)"
                >
                  ✕
                </button>
              </div>
            </div>
            <button class="add-task-btn mt-2" @click="addBonReviewer">
              + Add Reviewer Slot
            </button>
          </div>

          <!-- Final Applier -->
          <div class="form-group">
            <label>Final Applier Model</label>
            <select
              v-model="form.bonFinalApplierModel"
              class="form-select"
              @change="markModified('bestOfNConfig')"
            >
              <option
                v-for="opt in modelSearch.getModelOptions(form.bonFinalApplierModel || 'default')"
                :key="opt.value"
                :value="opt.value"
              >
                {{ opt.label }}
              </option>
            </select>
          </div>

          <div class="form-group">
            <label>Final Applier Suffix (optional)</label>
            <textarea
              v-model="form.bonFinalApplierSuffix"
              class="form-textarea"
              placeholder="Additional instructions for the final applier..."
              @change="markModified('bestOfNConfig')"
            />
          </div>

          <!-- Selection Mode & Min Successful -->
          <div class="grid grid-cols-2 gap-3">
            <div class="form-group">
              <label>Selection Mode</label>
              <select 
                v-model="form.bonSelectionMode" 
                class="form-select"
                @change="markModified('bestOfNConfig')"
              >
                <option value="pick_best">Pick Best</option>
                <option value="synthesize">Synthesize</option>
                <option value="pick_or_synthesize">Pick or Synthesize</option>
              </select>
            </div>
            <div class="form-group">
              <label>Min Successful Workers</label>
              <input
                v-model.number="form.bonMinSuccessful"
                type="number"
                min="1"
                max="8"
                class="form-input"
                @change="markModified('bestOfNConfig')"
              />
            </div>
          </div>

          <!-- Verification Command -->
          <div class="form-group">
            <label>Verification Command (optional)</label>
            <input
              v-model="form.bonVerificationCmd"
              type="text"
              class="form-input"
              placeholder="e.g. npm test"
              @change="markModified('bestOfNConfig')"
            />
          </div>
        </div>

        <div v-else-if="form.executionStrategy === 'best_of_n' && !form.bonConfigEnabled" class="text-sm text-amber-400">
          Best-of-N configuration can only be edited when all selected tasks use the "Best of N" strategy.
        </div>

        <!-- Max Review Override -->
        <div class="form-group">
          <div class="label-row">
            <label>Max Review Runs Override</label>
            <span v-if="form.maxReviewRunsOverrideMixed" class="text-xs text-amber-400">(mixed)</span>
          </div>
          <input
            v-model.number="form.maxReviewRunsOverride"
            type="number"
            min="1"
            class="form-input"
            :placeholder="form.maxReviewRunsOverrideMixed ? '— (mixed values)' : 'Use global default'"
            @change="markModified('maxReviewRunsOverride')"
          />
        </div>

        <!-- Checkboxes -->
        <div class="checkbox-group">
          <label class="checkbox-item">
            <input 
              v-model="form.planmode" 
              :indeterminate="form.planmode === undefined && form.planmodeMixed"
              type="checkbox"
              @change="markModified('planmode')"
            />
            <span>
              Plan Mode
              <span v-if="form.planmodeMixed" class="text-xs text-amber-400 ml-1">(mixed)</span>
            </span>
          </label>
          <label class="checkbox-item">
            <input 
              v-model="form.autoApprovePlan" 
              :indeterminate="form.autoApprovePlan === undefined && form.autoApprovePlanMixed"
              type="checkbox"
              @change="markModified('autoApprovePlan')"
            />
            <span>
              Auto-approve plan
              <span v-if="form.autoApprovePlanMixed" class="text-xs text-amber-400 ml-1">(mixed)</span>
            </span>
          </label>
          <label class="checkbox-item">
            <input 
              v-model="form.review" 
              :indeterminate="form.review === undefined && form.reviewMixed"
              type="checkbox"
              @change="markModified('review')"
            />
            <span>
              Review
              <span v-if="form.reviewMixed" class="text-xs text-amber-400 ml-1">(mixed)</span>
            </span>
          </label>
          <label class="checkbox-item">
            <input 
              v-model="form.autoCommit" 
              :indeterminate="form.autoCommit === undefined && form.autoCommitMixed"
              type="checkbox"
              @change="markModified('autoCommit')"
            />
            <span>
              Auto-commit
              <span v-if="form.autoCommitMixed" class="text-xs text-amber-400 ml-1">(mixed)</span>
            </span>
          </label>
          <label class="checkbox-item">
            <input 
              v-model="form.deleteWorktree" 
              :indeterminate="form.deleteWorktree === undefined && form.deleteWorktreeMixed"
              type="checkbox"
              @change="markModified('deleteWorktree')"
            />
            <span>
              Delete Worktree
              <span v-if="form.deleteWorktreeMixed" class="text-xs text-amber-400 ml-1">(mixed)</span>
            </span>
          </label>
          <label class="checkbox-item">
            <input 
              v-model="form.skipPermissionAsking" 
              :indeterminate="form.skipPermissionAsking === undefined && form.skipPermissionAskingMixed"
              type="checkbox"
              @change="markModified('skipPermissionAsking')"
            />
            <span>
              Skip Permission Asking
              <span v-if="form.skipPermissionAskingMixed" class="text-xs text-amber-400 ml-1">(mixed)</span>
            </span>
          </label>
        </div>
      </div>

      <div class="modal-footer">
        <button class="btn" @click="emit('close')">Cancel</button>
        <button
          class="btn btn-primary"
          :disabled="isLoading || modifiedFields.size === 0"
          @click="save"
        >
          {{ isLoading ? 'Saving...' : `Update ${selectedCount} Tasks` }}
        </button>
      </div>
    </div>
  </div>
</template>
