// src/kanban-react/src/components/modals/ExecutionGraphModal.tsx
import { useState, useEffect } from 'react'
import { ModalWrapper } from '../common/ModalWrapper'
import { useOptionsContext, useToastContext } from '@/contexts/AppContext'
import { useApi } from '@/hooks'
import type { ExecutionGraph } from '@/types'

interface ExecutionGraphModalProps {
  onClose: () => void
}

export function ExecutionGraphModal({ onClose }: ExecutionGraphModalProps) {
  const options = useOptionsContext()
  const toasts = useToastContext()
  const api = useApi()

  const [graph, setGraph] = useState<ExecutionGraph | null>(null)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    let cancelled = false
    const loadGraph = async () => {
      try {
        const data = await api.getExecutionGraph()
        if (!cancelled) setGraph(data)
      } catch (e) {
        if (!cancelled) {
          toasts.showToast('Failed to load execution graph: ' + (e instanceof Error ? e.message : String(e)), 'error')
        }
      } finally {
        if (!cancelled) setIsLoading(false)
      }
    }
    loadGraph()
    return () => { cancelled = true }
  }, [api, toasts])

  const startExecution = async () => {
    // Check if there are tasks to execute
    if (!graph || graph.totalTasks === 0) {
      toasts.showToast('No tasks available to execute. Create some tasks first.', 'error')
      return
    }
    try {
      await options.startExecution()
      onClose()
      toasts.showToast('Workflow run started', 'success')
    } catch (e) {
      toasts.showToast('Execution start failed: ' + (e instanceof Error ? e.message : String(e)), 'error')
    }
  }

  return (
    <ModalWrapper title="Execution Graph Preview" onClose={onClose} size="lg">
      <div className="space-y-4">
        {isLoading && (
          <div className="text-dark-text-muted">
            Loading execution graph...
          </div>
        )}

        {!isLoading && graph?.error && (
          <div className="text-red-400">
            {graph.error}
          </div>
        )}

        {!isLoading && graph && !graph.error && (
          <>
            {/* Summary */}
            <div className="text-sm text-dark-text-muted">
              {graph.totalTasks} task{graph.totalTasks !== 1 ? 's' : ''}
              {' '}in {graph.batches.length} batch{graph.batches.length !== 1 ? 'es' : ''}
              {' '}(parallel limit: {graph.parallelLimit})
            </div>

            {/* Run counts */}
            <div className="text-sm text-dark-text-muted p-2.5 border border-dark-surface3 rounded-lg bg-dark-bg">
              {graph.totalTasks} logical task{graph.totalTasks !== 1 ? 's' : ''},
              {' '}{graph.nodes.reduce((sum, n) => sum + (n.expandedWorkerRuns ?? 1), 0)} worker runs,
              {' '}{graph.nodes.reduce((sum, n) => sum + (n.expandedReviewerRuns ?? 0), 0)} reviewer runs,
              {' '}{graph.nodes.reduce((sum, n) => sum + (n.hasFinalApplier ? 1 : 0), 0)} final applier runs
            </div>

            {/* Warning for large runs */}
            {graph.nodes.reduce((sum, n) => sum + (n.estimatedRunCount ?? 1), 0) > 10 && (
              <div className="text-xs text-amber-400 p-2.5 border border-amber-500/45 rounded-lg bg-amber-500/10">
                Warning: this run plan expands to {graph.nodes.reduce((sum, n) => sum + (n.estimatedRunCount ?? 1), 0)}
                {' '}internal runs and may increase cost and total runtime.
              </div>
            )}

            {/* Batches */}
            <div className="flex flex-col gap-3">
              {graph.batches.map((batch) => (
                <div
                  key={batch.idx}
                  className="border border-dark-surface3 rounded-lg p-3 bg-dark-bg"
                >
                  <div className="text-xs font-semibold text-accent-primary mb-2">
                    Batch {batch.idx + 1} ({batch.taskNames.length} task{batch.taskNames.length !== 1 ? 's' : ''})
                  </div>
                  <div className="flex flex-col gap-1.5">
                    {batch.taskNames.map((taskName, i) => {
                      const node = graph.nodes.find(n => n.id === batch.taskIds[i])
                      return (
                        <div
                          key={i}
                          className="flex items-center gap-2 py-1"
                        >
                          <span className="text-dark-text-muted text-xs">▶</span>
                          <span className="text-sm">{taskName}</span>
                          {node?.hasFinalApplier && (
                            <span className="text-xs text-dark-text-muted">
                              (workers: {node?.expandedWorkerRuns || 0},
                              {' '}reviewers: {node?.expandedReviewerRuns || 0},
                              {' '}final applier: 1)
                            </span>
                          )}
                        </div>
                      )
                    })}
                  </div>
                </div>
              ))}
            </div>

            {/* Pending Approvals */}
            {graph.pendingApprovals?.length > 0 && (
              <div className="border border-green-500 rounded-lg p-3 bg-green-500/5">
                <div className="text-xs font-semibold text-green-400 mb-2">
                  Pending Approvals ({graph.pendingApprovals.length})
                </div>
                <div className="flex flex-col gap-1.5">
                  {graph.pendingApprovals.map((task) => (
                    <div
                      key={task.id}
                      className="flex items-center justify-between gap-2 py-1"
                    >
                      <div className="flex items-center gap-2">
                        <span className="text-green-400 text-xs">▶</span>
                        <span className="text-sm">
                          {task.name}{task.planRevisionCount > 0 ? ` (rev ${task.planRevisionCount})` : ''}
                        </span>
                      </div>
                      <div className="flex gap-1">
                        <button className="btn btn-sm border-green-500 text-green-400 hover:bg-green-500/10">
                          Approve
                        </button>
                        <button className="btn btn-sm border-orange-500 text-orange-400 hover:bg-orange-500/10">
                          Request Changes
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </>
        )}
      </div>

      <div className="modal-footer">
        <button className="btn" onClick={onClose}>Cancel</button>
        <button
          className="btn btn-primary"
          disabled={isLoading || !!graph?.error || !graph || graph.totalTasks === 0}
          onClick={startExecution}
        >
          Confirm & Start
        </button>
      </div>
    </ModalWrapper>
  )
}

// src/kanban-vue/src/components/modals/ExecutionGraphModal.vue
<script setup lang="ts">
import { ref, inject, onMounted } from 'vue'
import type { useOptions } from '@/composables/useOptions'
import type { useToasts } from '@/composables/useToasts'
import type { ExecutionGraph } from '@/types/api'

const emit = defineEmits<{
  close: []
}>()

const options = inject<ReturnType<typeof useOptions>>('options')!
const toasts = inject<ReturnType<typeof useToasts>>('toasts')!

const graph = ref<ExecutionGraph | null>(null)
const isLoading = ref(true)

onMounted(async () => {
  try {
    graph.value = await options.api.getExecutionGraph()
  } catch (e) {
    toasts.showToast('Failed to load execution graph: ' + (e instanceof Error ? e.message : String(e)), 'error')
  } finally {
    isLoading.value = false
  }
})

const startExecution = async () => {
  // Check if there are tasks to execute
  if (!graph.value || graph.value.totalTasks === 0) {
    toasts.showToast('No tasks available to execute. Create some tasks first.', 'error')
    return
  }
  try {
    await options.startExecution()
    emit('close')
    toasts.showToast('Workflow run started', 'success')
  } catch (e) {
    toasts.showToast('Execution start failed: ' + (e instanceof Error ? e.message : String(e)), 'error')
  }
}

const closeOnOverlay = (e: MouseEvent) => {
  if (e.target === e.currentTarget) {
    emit('close')
  }
}
</script>

<template>
  <div class="modal-overlay" @mousedown="closeOnOverlay">
    <div class="modal w-[600px]">
      <div class="modal-header">
        <h2>Execution Graph Preview</h2>
        <button class="modal-close" @click="emit('close')">×</button>
      </div>

      <div class="modal-body">
        <div v-if="isLoading" class="text-dark-text-muted">
          Loading execution graph...
        </div>

        <div v-else-if="graph?.error" class="text-red-400">
          {{ graph.error }}
        </div>

        <div v-else-if="graph">
          <!-- Summary -->
          <div class="mb-4 text-sm text-dark-text-muted">
            {{ graph.totalTasks }} task{{ graph.totalTasks !== 1 ? 's' : '' }}
            in {{ graph.batches.length }} batch{{ graph.batches.length !== 1 ? 'es' : '' }}
            (parallel limit: {{ graph.parallelLimit }})
          </div>

          <!-- Run counts -->
          <div class="mb-4 text-sm text-dark-text-muted p-2.5 border border-dark-surface3 rounded-lg bg-dark-bg">
            {{ graph.totalTasks }} logical task{{ graph.totalTasks !== 1 ? 's' : '' }},
            {{ graph.nodes.reduce((sum, n) => sum + (n.expandedWorkerRuns ?? 1), 0) }} worker runs,
            {{ graph.nodes.reduce((sum, n) => sum + (n.expandedReviewerRuns ?? 0), 0) }} reviewer runs,
            {{ graph.nodes.reduce((sum, n) => sum + (n.hasFinalApplier ? 1 : 0), 0) }} final applier runs
          </div>

          <!-- Warning for large runs -->
          <div
            v-if="graph.nodes.reduce((sum, n) => sum + (n.estimatedRunCount ?? 1), 0) > 10"
            class="mb-4 text-xs text-amber-400 p-2.5 border border-amber-500/45 rounded-lg bg-amber-500/10"
          >
            Warning: this run plan expands to {{ graph.nodes.reduce((sum, n) => sum + (n.estimatedRunCount ?? 1), 0) }}
            internal runs and may increase cost and total runtime.
          </div>

          <!-- Batches -->
          <div class="flex flex-col gap-3">
            <div
              v-for="batch in graph.batches"
              :key="batch.idx"
              class="border border-dark-surface3 rounded-lg p-3 bg-dark-bg"
            >
              <div class="text-xs font-semibold text-accent-primary mb-2">
                Batch {{ batch.idx + 1 }} ({{ batch.taskNames.length }} task{{ batch.taskNames.length !== 1 ? 's' : '' }})
              </div>
              <div class="flex flex-col gap-1.5">
                <div
                  v-for="(taskName, i) in batch.taskNames"
                  :key="i"
                  class="flex items-center gap-2 py-1"
                >
                  <span class="text-dark-text-muted text-xs">▶</span>
                  <span class="text-sm">{{ taskName }}</span>
                  <span
                    v-if="graph.nodes.find(n => n.id === batch.taskIds[i])?.hasFinalApplier"
                    class="text-xs text-dark-text-muted"
                  >
                    (workers: {{ graph.nodes.find(n => n.id === batch.taskIds[i])?.expandedWorkerRuns || 0 }},
                    reviewers: {{ graph.nodes.find(n => n.id === batch.taskIds[i])?.expandedReviewerRuns || 0 }},
                    final applier: 1)
                  </span>
                </div>
              </div>
            </div>
          </div>

          <!-- Pending Approvals -->
          <div
            v-if="graph.pendingApprovals?.length"
            class="mt-4 border border-green-500 rounded-lg p-3 bg-green-500/5"
          >
            <div class="text-xs font-semibold text-green-400 mb-2">
              Pending Approvals ({{ graph.pendingApprovals.length }})
            </div>
            <div class="flex flex-col gap-1.5">
              <div
                v-for="task in graph.pendingApprovals"
                :key="task.id"
                class="flex items-center justify-between gap-2 py-1"
              >
                <div class="flex items-center gap-2">
                  <span class="text-green-400 text-xs">▶</span>
                  <span class="text-sm">
                    {{ task.name }}{{ task.planRevisionCount > 0 ? ` (rev ${task.planRevisionCount})` : '' }}
                  </span>
                </div>
                <div class="flex gap-1">
                  <button class="btn btn-sm border-green-500 text-green-400 hover:bg-green-500/10">
                    Approve
                  </button>
                  <button class="btn btn-sm border-orange-500 text-orange-400 hover:bg-orange-500/10">
                    Request Changes
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button class="btn" @click="emit('close')">Cancel</button>
        <button class="btn btn-primary" :disabled="isLoading || !!graph?.error || !graph || graph.totalTasks === 0" @click="startExecution">
          Confirm & Start
        </button>
      </div>
    </div>
  </div>
</template>
