// src/kanban-react/src/components/modals/TaskModal.tsx
import { useState, useEffect } from 'react'
import { ModalWrapper } from '../common/ModalWrapper'
import { ModelPicker } from '../common/ModelPicker'
import { ThinkingLevelSelect } from '../common/ThinkingLevelSelect'
import { MarkdownEditor } from '../common/MarkdownEditor'
import { useTasksContext, useOptionsContext, useModelSearchContext, useToastContext } from '@/contexts/AppContext'
import { useApi } from '@/hooks'
import type { Task, TaskStatus, ThinkingLevel, ExecutionStrategy, BestOfNSlot } from '@/types'

interface TaskModalProps {
  mode: 'create' | 'edit' | 'deploy' | 'view'
  taskId?: string
  createStatus?: 'template' | 'backlog'
  seedTaskId?: string
  onClose: () => void
}

export function TaskModal({ mode, taskId, createStatus = 'backlog', seedTaskId, onClose }: TaskModalProps) {
  const tasks = useTasksContext()
  const optionsContext = useOptionsContext()
  const modelSearch = useModelSearchContext()
  const toasts = useToastContext()
  const api = useApi()
  const getBranches = api.getBranches
  const getContainerImages = api.getContainerImages

  const existingTask = taskId ? tasks.getTaskById(taskId) : null
  const seedTask = seedTaskId ? tasks.getTaskById(seedTaskId) : null

  const [name, setName] = useState(existingTask?.name || seedTask?.name || '')
  const [prompt, setPrompt] = useState(existingTask?.prompt || seedTask?.prompt || '')
  const [branch, setBranch] = useState('')
  const [planModel, setPlanModel] = useState(existingTask?.planModel || optionsContext.options?.planModel || '')
  const [executionModel, setExecutionModel] = useState(existingTask?.executionModel || optionsContext.options?.executionModel || '')
  const [thinkingLevel, setThinkingLevel] = useState<ThinkingLevel>(existingTask?.thinkingLevel || optionsContext.options?.thinkingLevel || 'default')
  const [planThinkingLevel, setPlanThinkingLevel] = useState<ThinkingLevel>(existingTask?.planThinkingLevel || optionsContext.options?.planThinkingLevel || 'default')
  const [executionThinkingLevel, setExecutionThinkingLevel] = useState<ThinkingLevel>(existingTask?.executionThinkingLevel || optionsContext.options?.executionThinkingLevel || 'default')
  const [planmode, setPlanmode] = useState(existingTask?.planmode ?? false)
  const [autoApprovePlan, setAutoApprovePlan] = useState(existingTask?.autoApprovePlan ?? false)
  const [review, setReview] = useState(existingTask?.review ?? true)
  const [autoCommit, setAutoCommit] = useState(existingTask?.autoCommit ?? true)
  const [deleteWorktree, setDeleteWorktree] = useState(existingTask?.deleteWorktree ?? true)
  const [skipPermissionAsking, setSkipPermissionAsking] = useState(existingTask?.skipPermissionAsking ?? true)
  const [requirements, setRequirements] = useState<string[]>(existingTask?.requirements || seedTask?.requirements || [])
  const [executionStrategy, setExecutionStrategy] = useState<ExecutionStrategy>(existingTask?.executionStrategy || 'standard')
  const [containerImage, setContainerImage] = useState(existingTask?.containerImage || '')
  const [availableBranches, setAvailableBranches] = useState<string[]>([])
  const [availableImages, setAvailableImages] = useState<Array<{ tag: string }>>([])
  const [isLoading, setIsLoading] = useState(true)
  const [bonWorkers, setBonWorkers] = useState<BestOfNSlot[]>([])
  const [bonReviewers, setBonReviewers] = useState<BestOfNSlot[]>([])
  const [bonFinalApplierModel, setBonFinalApplierModel] = useState('')
  const [bonFinalApplierSuffix, setBonFinalApplierSuffix] = useState('')
  const [bonSelectionMode, setBonSelectionMode] = useState<'pick_best' | 'synthesize' | 'pick_or_synthesize'>('pick_best')
  const [bonMinSuccessful, setBonMinSuccessful] = useState(1)
  const [bonVerificationCmd, setBonVerificationCmd] = useState('')

  const isViewOnly = mode === 'view'
  const isDeploy = mode === 'deploy'
  const isCreate = mode === 'create'
  const isEdit = mode === 'edit'

  const showBonConfig = executionStrategy === 'best_of_n'

  useEffect(() => {
    let cancelled = false
    const loadData = async () => {
      setIsLoading(true)
      try {
        const [branchData, imageData] = await Promise.all([
          getBranches(),
          getContainerImages()
        ])
        if (cancelled) return

        setAvailableBranches(branchData.branches || [])
        setAvailableImages(imageData.images || [])

        if (existingTask?.branch) {
          setBranch(existingTask.branch)
        } else if (seedTask?.branch) {
          setBranch(seedTask.branch)
        } else if (branchData.current) {
          setBranch(branchData.current)
        } else if (branchData.branches?.[0]) {
          setBranch(branchData.branches[0])
        }

        if (existingTask?.containerImage) {
          setContainerImage(existingTask.containerImage)
        } else if (optionsContext.options?.container?.image) {
          setContainerImage(optionsContext.options.container.image)
        }

        if (existingTask?.executionStrategy === 'best_of_n' && existingTask.bestOfNConfig) {
          setBonWorkers(existingTask.bestOfNConfig.workers.map(w => ({ ...w })))
          setBonReviewers(existingTask.bestOfNConfig.reviewers.map(r => ({ ...r })))
          setBonFinalApplierModel(existingTask.bestOfNConfig.finalApplier.model)
          setBonFinalApplierSuffix(existingTask.bestOfNConfig.finalApplier.taskSuffix || '')
          setBonSelectionMode(existingTask.bestOfNConfig.selectionMode)
          setBonMinSuccessful(existingTask.bestOfNConfig.minSuccessfulWorkers)
          setBonVerificationCmd(existingTask.bestOfNConfig.verificationCommand || '')
        }
      } catch (e) {
        console.error('Failed to load data:', e)
      } finally {
        if (!cancelled) setIsLoading(false)
      }
    }
    loadData()
    return () => { cancelled = true }
  }, [getBranches, getContainerImages, existingTask, seedTask, optionsContext.options])

  // Show backlog tasks for adding new dependencies
  // Also show done tasks that are already dependencies so they can be removed
  const availableRequirements = tasks.tasks.filter(t => {
    if (isViewOnly) return t.id !== taskId
    if (t.id === taskId) return false
    // Always show backlog tasks as potential new dependencies
    if (t.status === 'backlog') return true
    // Show done tasks only if they are already in requirements (so they can be removed)
    if (t.status === 'done' && requirements.includes(t.id)) return true
    return false
  })

  const addBonWorker = () => {
    setBonWorkers([...bonWorkers, { model: '', count: 1, suffix: '' }])
  }

  const removeBonWorker = (index: number) => {
    setBonWorkers(bonWorkers.filter((_, i) => i !== index))
  }

  const updateBonWorker = (index: number, field: 'model' | 'count' | 'suffix', value: string | number) => {
    setBonWorkers(bonWorkers.map((w, i) => i === index ? { ...w, [field]: value } : w))
  }

  const addBonReviewer = () => {
    setBonReviewers([...bonReviewers, { model: '', count: 1, suffix: '' }])
  }

  const removeBonReviewer = (index: number) => {
    setBonReviewers(bonReviewers.filter((_, i) => i !== index))
  }

  const updateBonReviewer = (index: number, field: 'model' | 'count' | 'suffix', value: string | number) => {
    setBonReviewers(bonReviewers.map((r, i) => i === index ? { ...r, [field]: value } : r))
  }

  const toggleRequirement = (taskId: string) => {
    setRequirements(prev =>
      prev.includes(taskId) ? prev.filter(id => id !== taskId) : [...prev, taskId]
    )
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!name.trim() || !prompt.trim()) {
      toasts.showToast('Name and prompt are required', 'error')
      return
    }

    if (!branch) {
      toasts.showToast('Select a valid branch', 'error')
      return
    }

    if (executionStrategy === 'best_of_n') {
      if (bonWorkers.length === 0) {
        toasts.showToast('Add at least one worker slot for Best of N', 'error')
        return
      }
      const totalWorkers = bonWorkers.reduce((sum, w) => sum + (w.count || 1), 0)
      if (totalWorkers > 8) {
        toasts.showToast(`Total workers (${totalWorkers}) exceeds maximum of 8`, 'error')
        return
      }
      if (bonMinSuccessful > totalWorkers) {
        toasts.showToast('Minimum successful workers cannot exceed total workers', 'error')
        return
      }
    }

    try {
      const taskData: Record<string, unknown> = {
        name: name.trim(),
        prompt: prompt.trim(),
        branch,
        planModel: modelSearch.normalizeValue(planModel),
        executionModel: modelSearch.normalizeValue(executionModel),
        planmode,
        autoApprovePlan,
        review,
        autoCommit,
        deleteWorktree,
        skipPermissionAsking,
        requirements,
        thinkingLevel,
        planThinkingLevel,
        executionThinkingLevel,
        executionStrategy,
        containerImage: containerImage || undefined,
      }

      if (executionStrategy === 'best_of_n') {
        taskData.bestOfNConfig = {
          workers: bonWorkers.map(w => ({
            model: w.model,
            count: w.count || 1,
            taskSuffix: w.suffix || undefined,
          })),
          reviewers: bonReviewers.map(r => ({
            model: r.model,
            count: r.count || 1,
            taskSuffix: r.suffix || undefined,
          })),
          finalApplier: {
            model: modelSearch.normalizeValue(bonFinalApplierModel),
            taskSuffix: bonFinalApplierSuffix.trim() || undefined,
          },
          selectionMode: bonSelectionMode,
          minSuccessfulWorkers: bonMinSuccessful,
          verificationCommand: bonVerificationCmd.trim() || undefined,
        }
      }

      if (isEdit && taskId) {
        await tasks.updateTask(taskId, taskData)
        toasts.showToast('Task updated', 'success')
      } else if (isDeploy && seedTaskId) {
        await tasks.createTask({ ...taskData, status: 'backlog' })
        toasts.showToast('Template deployed', 'success')
      } else {
        await tasks.createTask({ ...taskData, status: createStatus })
        toasts.showToast('Task created', 'success')
      }
      onClose()
    } catch (e) {
      toasts.showToast(e instanceof Error ? e.message : 'Failed to save task', 'error')
    }
  }

  const getTitle = () => {
    if (isViewOnly) return 'View Task'
    if (isDeploy) return 'Deploy Template'
    if (isEdit) return createStatus === 'template' ? 'Edit Template' : 'Edit Task'
    return createStatus === 'template' ? 'Add Template' : 'Add Task'
  }

  const getSaveButtonText = () => {
    if (isDeploy) return 'Send to Backlog'
    if (isCreate && createStatus === 'template') return 'Save Template'
    return 'Save'
  }

  if (isLoading) {
    return (
      <ModalWrapper title={getTitle()} onClose={onClose} size="lg">
        <div className="p-8 text-center">
          <div className="text-dark-text-muted">Loading...</div>
        </div>
      </ModalWrapper>
    )
  }

  return (
    <ModalWrapper title={getTitle()} onClose={onClose} size="lg">
      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Name */}
        <div className="form-group">
          <div className="label-row">
            <label>Name</label>
            <span className="help-btn" title="Short task title shown on the card.">?</span>
          </div>
          <input
            type="text"
            className="form-input"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Task name"
            disabled={isViewOnly}
            required
          />
        </div>

        {/* Prompt */}
        <div className="form-group">
          <div className="label-row">
            <label>Prompt</label>
            <span className="help-btn" title="The main instructions for the agent.">?</span>
          </div>
          <MarkdownEditor
            modelValue={prompt}
            onUpdate={setPrompt}
            placeholder="What should this task do?"
            disabled={isViewOnly}
          />
        </div>

        {/* Models with Thinking Levels */}
        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-2">
            <ModelPicker
              modelValue={planModel}
              label="Plan Model"
              help="Model used for planning steps before implementation."
              disabled={isViewOnly}
              onUpdate={setPlanModel}
            />
            <ThinkingLevelSelect
              modelValue={planThinkingLevel}
              label="Plan Thinking"
              help="Thinking level for planning phase."
              disabled={isViewOnly}
              onUpdate={(v) => setPlanThinkingLevel(v as ThinkingLevel)}
            />
          </div>
          <div className="space-y-2">
            <ModelPicker
              modelValue={executionModel}
              label="Execution Model"
              help="Model used for the actual implementation work."
              disabled={isViewOnly}
              onUpdate={setExecutionModel}
            />
            <ThinkingLevelSelect
              modelValue={executionThinkingLevel}
              label="Execution Thinking"
              help="Thinking level for execution phase."
              disabled={isViewOnly}
              onUpdate={(v) => setExecutionThinkingLevel(v as ThinkingLevel)}
            />
          </div>
        </div>

        {/* Execution Strategy */}
        <div className="form-group">
          <div className="label-row">
            <label>Execution Strategy</label>
            <span className="help-btn" title="Standard runs a single execution. Best of N runs multiple candidates in parallel and picks or synthesizes the best result.">?</span>
          </div>
          <select
            className="form-select"
            value={executionStrategy}
            onChange={(e) => setExecutionStrategy(e.target.value as ExecutionStrategy)}
            disabled={isViewOnly}
          >
            <option value="standard">Standard</option>
            <option value="best_of_n">Best of N</option>
          </select>
        </div>

        {/* Container Image */}
        <div className="form-group">
          <div className="label-row">
            <label>Container Image</label>
            <span className="help-btn" title="Select the container image for this task. Uses system default if not specified.">?</span>
          </div>
          <select
            className="form-select"
            value={containerImage}
            onChange={(e) => setContainerImage(e.target.value)}
            disabled={isViewOnly}
          >
            <option value="">System Default</option>
            {availableImages.map(img => (
              <option key={img.tag} value={img.tag}>{img.tag}</option>
            ))}
          </select>
          {availableImages.length > 0 && (
            <div className="text-xs text-dark-text-muted mt-1">Build custom images in the Image Builder</div>
          )}
        </div>

        {/* Best-of-N Config */}
        {showBonConfig && (
          <div className="border border-dark-surface3 rounded-lg p-3 bg-dark-bg">
            <h4 className="text-sm font-semibold mb-2">Best of N Configuration</h4>

            {/* Workers */}
            <div className="form-group">
              <label>Workers</label>
              <div className="space-y-2">
                {bonWorkers.map((slot, i) => (
                  <div key={i} className="flex gap-2 items-center">
                    <input
                      type="number"
                      min={1}
                      max={4}
                      className="form-input w-16"
                      value={slot.count || 1}
                      onChange={(e) => updateBonWorker(i, 'count', parseInt(e.target.value) || 1)}
                      disabled={isViewOnly}
                    />
                    <select
                      className="form-select flex-1"
                      value={slot.model}
                      onChange={(e) => updateBonWorker(i, 'model', e.target.value)}
                      disabled={isViewOnly}
                    >
                      <option value="">Select model...</option>
                      {modelSearch.getModelOptions(slot.model).map(opt => (
                        <option key={opt.value} value={opt.value}>{opt.label}</option>
                      ))}
                    </select>
                    <input
                      type="text"
                      placeholder="Suffix (optional)"
                      className="form-input flex-1"
                      value={slot.suffix || ''}
                      onChange={(e) => updateBonWorker(i, 'suffix', e.target.value)}
                      disabled={isViewOnly}
                    />
                    {!isViewOnly && (
                      <button
                        type="button"
                        className="text-red-400 hover:text-red-300 px-2"
                        onClick={() => removeBonWorker(i)}
                      >
                        ✕
                      </button>
                    )}
                  </div>
                ))}
              </div>
              {!isViewOnly && (
                <button type="button" className="add-task-btn mt-2" onClick={addBonWorker}>
                  + Add Worker Slot
                </button>
              )}
            </div>

            {/* Reviewers */}
            <div className="form-group">
              <label>Reviewers</label>
              <div className="space-y-2">
                {bonReviewers.map((slot, i) => (
                  <div key={i} className="flex gap-2 items-center">
                    <input
                      type="number"
                      min={1}
                      max={4}
                      className="form-input w-16"
                      value={slot.count || 1}
                      onChange={(e) => updateBonReviewer(i, 'count', parseInt(e.target.value) || 1)}
                      disabled={isViewOnly}
                    />
                    <select
                      className="form-select flex-1"
                      value={slot.model}
                      onChange={(e) => updateBonReviewer(i, 'model', e.target.value)}
                      disabled={isViewOnly}
                    >
                      <option value="">Select model...</option>
                      {modelSearch.getModelOptions(slot.model).map(opt => (
                        <option key={opt.value} value={opt.value}>{opt.label}</option>
                      ))}
                    </select>
                    <input
                      type="text"
                      placeholder="Suffix (optional)"
                      className="form-input flex-1"
                      value={slot.suffix || ''}
                      onChange={(e) => updateBonReviewer(i, 'suffix', e.target.value)}
                      disabled={isViewOnly}
                    />
                    {!isViewOnly && (
                      <button
                        type="button"
                        className="text-red-400 hover:text-red-300 px-2"
                        onClick={() => removeBonReviewer(i)}
                      >
                        ✕
                      </button>
                    )}
                  </div>
                ))}
              </div>
              {!isViewOnly && (
                <button type="button" className="add-task-btn mt-2" onClick={addBonReviewer}>
                  + Add Reviewer Slot
                </button>
              )}
            </div>

            {/* Final Applier */}
            <ModelPicker
              modelValue={bonFinalApplierModel}
              label="Final Applier Model"
              disabled={isViewOnly}
              onUpdate={setBonFinalApplierModel}
            />

            <div className="form-group">
              <label>Final Applier Suffix (optional)</label>
              <textarea
                className="form-textarea"
                placeholder="Additional instructions for the final applier..."
                value={bonFinalApplierSuffix}
                onChange={(e) => setBonFinalApplierSuffix(e.target.value)}
                disabled={isViewOnly}
              />
            </div>

            {/* Selection Mode & Min Successful */}
            <div className="grid grid-cols-2 gap-3">
              <div className="form-group">
                <label>Selection Mode</label>
                <select
                  className="form-select"
                  value={bonSelectionMode}
                  onChange={(e) => setBonSelectionMode(e.target.value as typeof bonSelectionMode)}
                  disabled={isViewOnly}
                >
                  <option value="pick_best">Pick Best</option>
                  <option value="synthesize">Synthesize</option>
                  <option value="pick_or_synthesize">Pick or Synthesize</option>
                </select>
              </div>
              <div className="form-group">
                <label>Min Successful Workers</label>
                <input
                  type="number"
                  min={1}
                  max={8}
                  className="form-input"
                  value={bonMinSuccessful}
                  onChange={(e) => setBonMinSuccessful(parseInt(e.target.value) || 1)}
                  disabled={isViewOnly}
                />
              </div>
            </div>

            {/* Verification Command */}
            <div className="form-group">
              <label>Verification Command (optional)</label>
              <input
                type="text"
                className="form-input"
                placeholder="e.g. npm test"
                value={bonVerificationCmd}
                onChange={(e) => setBonVerificationCmd(e.target.value)}
                disabled={isViewOnly}
              />
            </div>
          </div>
        )}

        {/* Branch */}
        <div className="form-group">
          <div className="label-row">
            <label>Branch</label>
            <span className="help-btn" title="Git branch the task should run against.">?</span>
          </div>
          <select
            className="form-select"
            value={branch}
            onChange={(e) => setBranch(e.target.value)}
            disabled={isViewOnly}
          >
            {availableBranches.map(b => (
              <option key={b} value={b}>{b}</option>
            ))}
          </select>
        </div>

        {/* Checkboxes */}
        {!isViewOnly && (
          <div className="checkbox-group">
            <label className="checkbox-item">
              <input type="checkbox" checked={planmode} onChange={(e) => setPlanmode(e.target.checked)} />
              <span>Plan Mode</span>
            </label>
            <label className="checkbox-item">
              <input type="checkbox" checked={autoApprovePlan} onChange={(e) => setAutoApprovePlan(e.target.checked)} />
              <span>Auto-approve plan</span>
            </label>
            <label className="checkbox-item">
              <input type="checkbox" checked={review} onChange={(e) => setReview(e.target.checked)} />
              <span>Review</span>
            </label>
            <label className="checkbox-item">
              <input type="checkbox" checked={autoCommit} onChange={(e) => setAutoCommit(e.target.checked)} />
              <span>Auto-commit</span>
            </label>
            <label className="checkbox-item">
              <input type="checkbox" checked={deleteWorktree} onChange={(e) => setDeleteWorktree(e.target.checked)} />
              <span>Delete Worktree</span>
            </label>
            <label className="checkbox-item">
              <input type="checkbox" checked={skipPermissionAsking} onChange={(e) => setSkipPermissionAsking(e.target.checked)} />
              <span>Skip Permission Asking</span>
            </label>
          </div>
        )}

        {/* Requirements */}
        <div className="form-group">
          <div className="label-row">
            <label>Requirements (dependencies)</label>
            <span className="help-btn" title="Tasks that must be completed before this one should run.">?</span>
          </div>
          <div className="border border-dark-surface3 rounded-lg p-1.5 max-h-36 overflow-y-auto">
            {availableRequirements.map(t => (
              <label
                key={t.id}
                className="checkbox-item p-1 rounded hover:bg-dark-surface2"
              >
                <input
                  type="checkbox"
                  checked={requirements.includes(t.id)}
                  onChange={() => toggleRequirement(t.id)}
                  disabled={isViewOnly}
                />
                <span className="text-sm">{t.name} (#{t.idx + 1})</span>
              </label>
            ))}
            {availableRequirements.length === 0 && (
              <div className="text-xs text-dark-text-muted p-1">No other tasks</div>
            )}
          </div>
        </div>

        <div className="modal-footer">
          <button type="button" className="btn" onClick={onClose}>Cancel</button>
          {!isViewOnly && (
            <button type="submit" className="btn btn-primary">
              {getSaveButtonText()}
            </button>
          )}
        </div>
      </form>
    </ModalWrapper>
  )
}

// src/kanban-vue/src/components/modals/TaskModal.vue
<script setup lang="ts">
import { ref, computed, inject, watch, onMounted } from 'vue'
import type { Task, CreateTaskDTO, BestOfNSlot, BestOfNConfig } from '@/types/api'
import type { useTasks } from '@/composables/useTasks'
import type { useModelSearch } from '@/composables/useModelSearch'
import type { useToasts } from '@/composables/useToasts'
import type { useOptions } from '@/composables/useOptions'
import ModelPicker from '../common/ModelPicker.vue'
import ThinkingLevelSelect from '../common/ThinkingLevelSelect.vue'
import MarkdownEditor from '../common/MarkdownEditor.vue'

const props = defineProps<{
  mode: 'create' | 'edit' | 'view' | 'deploy'
  taskId?: string
  createStatus: 'template' | 'backlog'
  seedTaskId?: string
}>()

const emit = defineEmits<{
  close: []
}>()

const tasks = inject<ReturnType<typeof useTasks>>('tasks')!
const modelSearch = inject<ReturnType<typeof useModelSearch>>('modelSearch')!
const toasts = inject<ReturnType<typeof useToasts>>('toasts')!
const options = inject<ReturnType<typeof useOptions>>('options')!

const form = ref({
  name: '',
  prompt: '',
  branch: '',
  planModel: '',
  executionModel: '',
  planmode: false,
  autoApprovePlan: false,
  review: true,
  autoCommit: true,
  deleteWorktree: true,
  skipPermissionAsking: true,
  requirements: [] as string[],
  thinkingLevel: 'default' as const,
  planThinkingLevel: 'default' as const,
  executionThinkingLevel: 'default' as const,
  executionStrategy: 'standard' as const,
  bonWorkers: [] as BestOfNSlot[],
  bonReviewers: [] as BestOfNSlot[],
  bonFinalApplierModel: '',
  bonFinalApplierSuffix: '',
  bonSelectionMode: 'pick_best' as const,
  bonMinSuccessful: 1,
  bonVerificationCmd: '',
  containerImage: '',
})

const bonValidationErrors = ref<string[]>([])
const isLoading = ref(false)
const isInitializing = ref(true)

const isViewOnly = computed(() => props.mode === 'view')
const isDeploy = computed(() => props.mode === 'deploy')
const isCreate = computed(() => props.mode === 'create')
const isEdit = computed(() => props.mode === 'edit')

const title = computed(() => {
  if (isViewOnly.value) return 'View Task'
  if (isDeploy.value) return 'Deploy Template'
  if (isEdit.value) return props.createStatus === 'template' ? 'Edit Template' : 'Edit Task'
  return props.createStatus === 'template' ? 'Add Template' : 'Add Task'
})

const saveButtonText = computed(() => {
  if (isDeploy.value) return 'Send to Backlog'
  if (isCreate.value && props.createStatus === 'template') return 'Save Template'
  return 'Save'
})

const availableBranches = ref<string[]>([])
const currentBranch = ref<string | null>(null)
const availableImages = ref<Array<{ tag: string; createdAt: number; source: string; inUseByTasks: number }>>([])
const defaultImage = ref<string>('')

const populateFormFromTask = (task: Task) => {
  form.value.name = task.name
  form.value.prompt = task.prompt
  
  // Resolve branch: task.branch > currentBranch > availableBranches[0]
  if (task.branch) {
    form.value.branch = task.branch
  } else if (currentBranch.value) {
    form.value.branch = currentBranch.value
  } else if (availableBranches.value.length > 0) {
    form.value.branch = availableBranches.value[0]
  } else {
    throw new Error(`Cannot populate form: task '${task.id}' has no branch set and no branches are available`)
  }
  
  form.value.planModel = task.planModel
  form.value.executionModel = task.executionModel
  form.value.planmode = task.planmode
  form.value.autoApprovePlan = task.autoApprovePlan
  form.value.review = task.review
  form.value.autoCommit = task.autoCommit
  form.value.deleteWorktree = task.deleteWorktree !== false
  form.value.skipPermissionAsking = task.skipPermissionAsking
  form.value.requirements = [...task.requirements]
  form.value.thinkingLevel = task.thinkingLevel
  form.value.planThinkingLevel = task.planThinkingLevel
  form.value.executionThinkingLevel = task.executionThinkingLevel
  form.value.executionStrategy = task.executionStrategy
  form.value.containerImage = task.containerImage

  if (task.executionStrategy === 'best_of_n' && task.bestOfNConfig) {
    form.value.bonWorkers = task.bestOfNConfig.workers.map(w => ({ ...w }))
    form.value.bonReviewers = task.bestOfNConfig.reviewers.map(r => ({ ...r }))
    form.value.bonFinalApplierModel = task.bestOfNConfig.finalApplier.model
    form.value.bonFinalApplierSuffix = task.bestOfNConfig.finalApplier.taskSuffix
    form.value.bonSelectionMode = task.bestOfNConfig.selectionMode
    form.value.bonMinSuccessful = task.bestOfNConfig.minSuccessfulWorkers
    form.value.bonVerificationCmd = task.bestOfNConfig.verificationCommand
  }
}

const populateFormForNewTask = () => {
  const opts = options.options.value
  if (!opts) {
    throw new Error('Options not loaded: cannot populate form for new task')
  }
  
  if (!Array.isArray(availableBranches.value)) {
    throw new Error(`Invalid state: availableBranches must be an array, got ${typeof availableBranches.value}`)
  }
  
  const selectedBranch = currentBranch.value ?? availableBranches.value[0]
  if (selectedBranch === undefined) {
    throw new Error('No branch available: cannot populate form for new task')
  }
  form.value.branch = selectedBranch
  
  if (typeof opts.planModel !== 'string') {
    throw new Error(`Invalid options: 'planModel' must be a string, got ${typeof opts.planModel}`)
  }
  form.value.planModel = opts.planModel
  
  if (typeof opts.executionModel !== 'string') {
    throw new Error(`Invalid options: 'executionModel' must be a string, got ${typeof opts.executionModel}`)
  }
  form.value.executionModel = opts.executionModel
  
  return true
}

const loadAvailableImages = async () => {
  const response = await tasks.api.getContainerImages()
  if (!Array.isArray(response.images)) {
    throw new Error(`Invalid response: 'images' must be an array, got ${typeof response.images}`)
  }
  availableImages.value = response.images
  
  if (options.options.value?.container?.image) {
    defaultImage.value = options.options.value.container.image
  }
}

const initializeForm = async () => {
  isInitializing.value = true
  
  const [branchData] = await Promise.all([
    tasks.api.getBranches(),
    loadAvailableImages(),
  ])
  
  if (!Array.isArray(branchData.branches)) {
    throw new Error(`Invalid response: 'branches' must be an array, got ${typeof branchData.branches}`)
  }
  availableBranches.value = branchData.branches
  currentBranch.value = branchData.current ?? null
  
  if (props.taskId && (isEdit.value || isViewOnly.value)) {
    let task = tasks.getTaskById(props.taskId)
    if (!task) {
      task = await tasks.api.getTask(props.taskId)
    }
    if (!task) {
      throw new Error(`Task '${props.taskId}' not found`)
    }
    populateFormFromTask(task)
    isInitializing.value = false
  } else if (props.seedTaskId && isDeploy.value) {
    let seedTask = tasks.getTaskById(props.seedTaskId)
    if (!seedTask) {
      seedTask = await tasks.api.getTask(props.seedTaskId)
    }
    if (!seedTask) {
      throw new Error(`Template task '${props.seedTaskId}' not found`)
    }
    populateFormFromTask(seedTask)
    isInitializing.value = false
  } else if (isCreate.value) {
    if (!options.options.value) {
      await options.loadOptions()
    }
    populateFormForNewTask()
    isInitializing.value = false
  } else {
    isInitializing.value = false
  }
}

onMounted(() => {
  initializeForm()
})

const getFallbackBranch = () => {
  if (options.options?.value?.branch && availableBranches.value.includes(options.options.value.branch)) {
    return options.options.value.branch
  }
  if (currentBranch.value && availableBranches.value.includes(currentBranch.value)) {
    return currentBranch.value
  }
  const firstBranch = availableBranches.value[0]
  if (firstBranch === undefined) {
    throw new Error('No available branches found: cannot determine fallback branch')
  }
  return firstBranch
}

const availableRequirements = computed(() => {
  if (isViewOnly.value) {
    return tasks.tasks.value.filter(t => t.id !== props.taskId)
  }
  return tasks.tasks.value.filter(t => t.status === 'backlog' && t.id !== props.taskId)
})

const showBonConfig = computed(() => form.value.executionStrategy === 'best_of_n')

const validateBonConfig = (): string[] => {
  const errors: string[] = []
  if (form.value.bonWorkers.length === 0) {
    errors.push('Add at least one worker slot')
  }
  const totalWorkers = form.value.bonWorkers.reduce((sum, w) => sum + (w.count || 1), 0)
  if (totalWorkers > 8) {
    errors.push(`Total workers (${totalWorkers}) exceeds maximum of 8`)
  }
  if (form.value.bonMinSuccessful > totalWorkers) {
    errors.push('Minimum successful workers cannot exceed total workers')
  }
  return errors
}

const addBonWorker = () => {
  form.value.bonWorkers.push({ model: '', count: 1, suffix: '' })
}

const removeBonWorker = (index: number) => {
  form.value.bonWorkers.splice(index, 1)
}

const addBonReviewer = () => {
  form.value.bonReviewers.push({ model: '', count: 1, suffix: '' })
}

const removeBonReviewer = (index: number) => {
  form.value.bonReviewers.splice(index, 1)
}

const save = async () => {
  if (!form.value.name.trim() || !form.value.prompt.trim()) {
    toasts.showToast('Name and prompt are required', 'error')
    return
  }
  if (!form.value.branch) {
    toasts.showToast('Select a valid branch', 'error')
    return
  }

  if (form.value.executionStrategy === 'best_of_n') {
    const errors = validateBonConfig()
    if (errors.length > 0) {
      bonValidationErrors.value = errors
      toasts.showToast('Invalid best-of-n configuration: ' + errors.join('; '), 'error')
      return
    }
  }

  isLoading.value = true
  try {
    const data: CreateTaskDTO = {
      name: form.value.name.trim(),
      prompt: form.value.prompt.trim(),
      branch: form.value.branch,
      planModel: modelSearch.normalizeValue(form.value.planModel),
      executionModel: modelSearch.normalizeValue(form.value.executionModel),
      planmode: form.value.planmode,
      autoApprovePlan: form.value.autoApprovePlan,
      review: form.value.review,
      autoCommit: form.value.autoCommit,
      deleteWorktree: form.value.deleteWorktree,
      skipPermissionAsking: form.value.skipPermissionAsking,
      requirements: form.value.requirements,
      thinkingLevel: form.value.thinkingLevel,
      planThinkingLevel: form.value.planThinkingLevel,
      executionThinkingLevel: form.value.executionThinkingLevel,
      executionStrategy: form.value.executionStrategy,
      containerImage: form.value.containerImage || undefined,
    }

    if (form.value.executionStrategy === 'best_of_n') {
      data.bestOfNConfig = {
        workers: form.value.bonWorkers.map(w => ({
          model: w.model,
          count: w.count || 1,
          taskSuffix: w.suffix || undefined,
        })),
        reviewers: form.value.bonReviewers.map(r => ({
          model: r.model,
          count: r.count || 1,
          taskSuffix: r.suffix || undefined,
        })),
        finalApplier: {
          model: modelSearch.normalizeValue(form.value.bonFinalApplierModel),
          taskSuffix: form.value.bonFinalApplierSuffix.trim() || undefined,
        },
        selectionMode: form.value.bonSelectionMode,
        minSuccessfulWorkers: form.value.bonMinSuccessful,
        verificationCommand: form.value.bonVerificationCmd.trim() || undefined,
      }
    }

    if (props.taskId && isEdit.value) {
      await tasks.updateTask(props.taskId, data)
    } else {
      await tasks.createTask({ ...data, status: props.createStatus })
      if (isDeploy.value) {
        toasts.showToast('Task sent to Backlog', 'success')
      }
    }

    emit('close')
  } catch (e) {
    toasts.showToast('Save failed: ' + (e instanceof Error ? e.message : String(e)), 'error')
  } finally {
    isLoading.value = false
  }
}

const closeOnOverlay = (e: MouseEvent) => {
  if (e.target === e.currentTarget) {
    emit('close')
  }
}
</script>

<template>
  <div class="modal-overlay" @mousedown="closeOnOverlay">
    <div class="modal w-[min(640px,calc(100vw-40px))] max-h-[min(880px,calc(100vh-40px))]">
      <div class="modal-header">
        <h2>{{ title }}</h2>
        <button class="modal-close" @click="emit('close')">×</button>
      </div>

      <!-- Loading State -->
      <div v-if="isInitializing" class="modal-body p-8 text-center">
        <div class="text-dark-text-muted">Loading...</div>
      </div>

      <template v-else>
        <div class="modal-body space-y-3">
          <!-- Name -->
          <div class="form-group">
            <div class="label-row">
              <label>Name</label>
              <span class="help-btn" title="Short task title shown on the card. Make it specific enough to identify the work at a glance.">?</span>
            </div>
            <input
              v-model="form.name"
              type="text"
              class="form-input"
              placeholder="Task name"
              :disabled="isViewOnly"
            />
          </div>

          <!-- Prompt -->
          <div class="form-group">
            <div class="label-row">
              <label>Prompt</label>
              <span class="help-btn" title="The main instructions for the agent. Describe the change, bug, or outcome you want it to produce.">?</span>
            </div>
            <MarkdownEditor
              v-model="form.prompt"
              :disabled="isViewOnly"
              placeholder="What should this task do?"
            />
          </div>

          <!-- Models with Thinking Levels -->
          <div class="grid grid-cols-2 gap-3">
            <div class="space-y-2">
              <ModelPicker
                v-model="form.planModel"
                label="Plan Model"
                help="Model used for planning steps before implementation. Use this when you want a specific model to reason about the approach first."
                :disabled="isViewOnly"
              />
              <ThinkingLevelSelect
                v-model="form.planThinkingLevel"
                label="Plan Thinking"
                help="Thinking level for planning phase. Higher levels provide more reasoning but take longer."
                :disabled="isViewOnly"
              />
            </div>
            <div class="space-y-2">
              <ModelPicker
                v-model="form.executionModel"
                label="Execution Model"
                help="Model used for the actual implementation work. Set this when execution should run on a different model than planning."
                :disabled="isViewOnly"
              />
              <ThinkingLevelSelect
                v-model="form.executionThinkingLevel"
                label="Execution Thinking"
                help="Thinking level for execution phase. Higher levels provide more reasoning but take longer."
                :disabled="isViewOnly"
              />
            </div>
          </div>

          <!-- Execution Strategy -->
          <div class="form-group">
            <div class="label-row">
              <label>Execution Strategy</label>
              <span class="help-btn" title="Standard runs a single execution. Best of N runs multiple candidates in parallel and picks or synthesizes the best result.">?</span>
            </div>
            <select v-model="form.executionStrategy" class="form-select" :disabled="isViewOnly">
              <option value="standard">Standard</option>
              <option value="best_of_n">Best of N</option>
            </select>
          </div>

          <!-- Container Image -->
          <div class="form-group">
            <div class="label-row">
              <label>Container Image</label>
              <span class="help-btn" title="Select the container image for this task. Uses system default if not specified.">?</span>
            </div>
            <select v-model="form.containerImage" class="form-select" :disabled="isViewOnly">
              <option value="">System Default {{ defaultImage ? `(${defaultImage})` : '' }}</option>
              <option 
                v-for="img in availableImages" 
                :key="img.tag" 
                :value="img.tag"
              >
                {{ img.tag }}
              </option>
            </select>
            <div v-if="availableImages.length > 0" class="text-xs text-dark-text-muted mt-1">
              Build custom images in the Image Builder
            </div>
          </div>

          <!-- Best-of-N Config -->
          <div v-if="showBonConfig" class="border border-dark-surface3 rounded-lg p-3 bg-dark-bg">
            <h4 class="text-sm font-semibold mb-2">Best of N Configuration</h4>

            <div v-if="bonValidationErrors.length > 0" class="mb-2 space-y-1">
              <div v-for="err in bonValidationErrors" :key="err" class="text-xs text-red-400">
                {{ err }}
              </div>
            </div>

            <!-- Workers -->
            <div class="form-group">
              <label>Workers</label>
              <div class="space-y-2">
                <div
                  v-for="(slot, i) in form.bonWorkers"
                  :key="i"
                  class="flex gap-2 items-center"
                >
                  <input
                    v-model.number="slot.count"
                    type="number"
                    min="1"
                    max="4"
                    class="form-input w-16"
                    :disabled="isViewOnly"
                  />
                  <select v-model="slot.model" class="form-select flex-1" :disabled="isViewOnly">
                    <option
                      v-for="opt in modelSearch.getModelOptions(slot.model)"
                      :key="opt.value"
                      :value="opt.value"
                      :selected="opt.selected"
                    >
                      {{ opt.label }}
                    </option>
                  </select>
                  <input
                    v-model="slot.suffix"
                    type="text"
                    placeholder="Suffix (optional)"
                    class="form-input flex-1"
                    :disabled="isViewOnly"
                  />
                  <button
                    v-if="!isViewOnly"
                    class="text-red-400 hover:text-red-300 px-2"
                    @click="removeBonWorker(i)"
                  >
                    ✕
                  </button>
                </div>
              </div>
              <button
                v-if="!isViewOnly"
                class="add-task-btn mt-2"
                @click="addBonWorker"
              >
                + Add Worker Slot
              </button>
            </div>

            <!-- Reviewers -->
            <div class="form-group">
              <label>Reviewers</label>
              <div class="space-y-2">
                <div
                  v-for="(slot, i) in form.bonReviewers"
                  :key="i"
                  class="flex gap-2 items-center"
                >
                  <input
                    v-model.number="slot.count"
                    type="number"
                    min="1"
                    max="4"
                    class="form-input w-16"
                    :disabled="isViewOnly"
                  />
                  <select v-model="slot.model" class="form-select flex-1" :disabled="isViewOnly">
                    <option
                      v-for="opt in modelSearch.getModelOptions(slot.model)"
                      :key="opt.value"
                      :value="opt.value"
                      :selected="opt.selected"
                    >
                      {{ opt.label }}
                    </option>
                  </select>
                  <input
                    v-model="slot.suffix"
                    type="text"
                    placeholder="Suffix (optional)"
                    class="form-input flex-1"
                    :disabled="isViewOnly"
                  />
                  <button
                    v-if="!isViewOnly"
                    class="text-red-400 hover:text-red-300 px-2"
                    @click="removeBonReviewer(i)"
                  >
                    ✕
                  </button>
                </div>
              </div>
              <button
                v-if="!isViewOnly"
                class="add-task-btn mt-2"
                @click="addBonReviewer"
              >
                + Add Reviewer Slot
              </button>
            </div>

            <!-- Final Applier -->
            <ModelPicker
              v-model="form.bonFinalApplierModel"
              label="Final Applier Model"
              :disabled="isViewOnly"
            />

            <div class="form-group">
              <label>Final Applier Suffix (optional)</label>
              <textarea
                v-model="form.bonFinalApplierSuffix"
                class="form-textarea"
                placeholder="Additional instructions for the final applier..."
                :disabled="isViewOnly"
              />
            </div>

            <!-- Selection Mode & Min Successful -->
            <div class="grid grid-cols-2 gap-3">
              <div class="form-group">
                <label>Selection Mode</label>
                <select v-model="form.bonSelectionMode" class="form-select" :disabled="isViewOnly">
                  <option value="pick_best">Pick Best</option>
                  <option value="synthesize">Synthesize</option>
                  <option value="pick_or_synthesize">Pick or Synthesize</option>
                </select>
              </div>
              <div class="form-group">
                <label>Min Successful Workers</label>
                <input
                  v-model.number="form.bonMinSuccessful"
                  type="number"
                  min="1"
                  max="8"
                  class="form-input"
                  :disabled="isViewOnly"
                />
              </div>
            </div>

            <!-- Verification Command -->
            <div class="form-group">
              <label>Verification Command (optional)</label>
              <input
                v-model="form.bonVerificationCmd"
                type="text"
                class="form-input"
                placeholder="e.g. npm test"
                :disabled="isViewOnly"
              />
            </div>
          </div>

          <!-- Branch -->
          <div class="form-group">
            <div class="label-row">
              <label>Branch</label>
              <span class="help-btn" title="Git branch the task should run against. Pick the branch where changes should be created or reviewed.">?</span>
            </div>
            <select v-model="form.branch" class="form-select" :disabled="isViewOnly">
              <option v-for="branch in availableBranches" :key="branch" :value="branch">
                {{ branch }}
              </option>
            </select>
          </div>

          <!-- Checkboxes -->
          <div class="checkbox-group" v-if="!isViewOnly">
            <label class="checkbox-item">
              <input v-model="form.planmode" type="checkbox" />
              <span>Plan Mode</span>
            </label>
            <label class="checkbox-item">
              <input v-model="form.autoApprovePlan" type="checkbox" />
              <span>Auto-approve plan</span>
            </label>
            <label class="checkbox-item">
              <input v-model="form.review" type="checkbox" />
              <span>Review</span>
            </label>
            <label class="checkbox-item">
              <input v-model="form.autoCommit" type="checkbox" />
              <span>Auto-commit</span>
            </label>
            <label class="checkbox-item">
              <input v-model="form.deleteWorktree" type="checkbox" />
              <span>Delete Worktree</span>
            </label>
            <label class="checkbox-item">
              <input v-model="form.skipPermissionAsking" type="checkbox" />
              <span>Skip Permission Asking</span>
            </label>
          </div>

          <!-- Requirements -->
          <div class="form-group">
            <div class="label-row">
              <label>Requirements (dependencies)</label>
              <span class="help-btn" title="Tasks that must be completed before this one should run. Use dependencies to enforce execution order.">?</span>
            </div>
            <div class="border border-dark-surface3 rounded-lg p-1.5 max-h-36 overflow-y-auto">
              <label
                v-for="t in availableRequirements"
                :key="t.id"
                class="checkbox-item p-1 rounded hover:bg-dark-surface2"
              >
                <input
                  v-model="form.requirements"
                  type="checkbox"
                  :value="t.id"
                  :disabled="isViewOnly"
                />
                <span class="text-sm">{{ t.name }} (#{{ t.idx + 1 }})</span>
              </label>
              <div v-if="availableRequirements.length === 0" class="text-xs text-dark-text-muted p-1">
                No other tasks
              </div>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button class="btn" @click="emit('close')">Cancel</button>
          <button
            v-if="!isViewOnly"
            class="btn btn-primary"
            :disabled="isLoading"
            @click="save"
          >
            {{ isLoading ? 'Saving...' : saveButtonText }}
          </button>
        </div>
      </template>
    </div>
  </div>
</template>
